/* -----------------------------------------------------------------------------
  Filename:    fbl_cfg.h
  Description: Toolversion: 06.05.00.01.11.00.95.02.00.00
               
               Serial Number: CBD1110095
               Customer Info: Nxtr
                              Package: Ford FNOS_I3_SLP6_FBL_wFlash
                              Micro: TexasInstruments TMS570
                              Compiler: Texas Instruments 4.9.0
               
               
               Generator Fwk   : GENy 
               Generator Module: GenTool_GenyFblCanBase
               
               Configuration   : C:\Synergy\ES_EPS_EA3_FBL_Haitec-dzxvzg\ES_EPS_EA3_FBL_Haitec\SwProject\GENy_files\GENyConfiguration_Haitec_570.gny
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "Channel0":
                       Databasefile: C:\Synergy_WorkArea\ES_EPS_EA3_FBL_Ford-tzj9qy\ES_EPS_EA3_FBL_Ford\GENy_files\FORD_HS2_CAN_S550_XCP.dbc
                       Bussystem:    CAN
                       Manufacturer: Ford
                       Node:         PSCM

  Generated by , 2013-07-18  11:50:05
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(__FBL_CFG_H__)
#define __FBL_CFG_H__

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#define FBL_ENABLE_STAY_IN_BOOT
#define FBL_DISABLE_FLASHBLOCK_CHECK
#define FBL_USE_OWN_MEMCPY
#define FBL_WATCHDOG_OFF
#define FBL_WATCHDOG_TIME                    (1 / FBL_REPEAT_CALL_CYCLE)
#define FBL_HEADER_ADDRESS                   0x0100
#define FBL_ENABLE_APPL_TASK
#define FBL_DIAG_BUFFER_LENGTH               1026
#define FBL_DIAG_TIME_P2MAX                  (25 / FBL_REPEAT_CALL_CYCLE)
#define FBL_DIAG_TIME_P3MAX                  (5000 / FBL_REPEAT_CALL_CYCLE)
#define kFillChar                            0xFF
#define FBL_DISABLE_MULTIPLE_MEM_DEVICES
/* Data Processing */
#define FBL_DISABLE_DATA_PROCESSING
#define FBL_DISABLE_COMPRESSION_MODE
/* Project State */
#define FBL_INTEGRATION                      2
#define FBL_PRODUCTION                       1
#define FBL_PROJECT_STATE                    FBL_INTEGRATION
#define FBL_ENABLE_SYSTEM_CHECK
#define FBL_ENABLE_DEBUG_STATUS
#define FBL_ENABLE_ASSERTION

/* Tmsx70DcanCrx specific **************************************************** */
#define FBL_TIMER_PRESCALER_VALUE            0x01
#define FBL_TIMER_RELOAD_VALUE               0x9C3F
#define DELAY                                60

#define CAN_BITTIMING                        0x2B89
#define CAN_BRP_REG                          0x00
#define CAN_CTRL_ADDR                        0xFFF7DC00
#define CAN_NUMBER_OF_HW_OBJECTS             64
#define CAN_TP_RXID                          0x730
#define CAN_TP_TXID                          0x738
#define CAN_TP_FUNC_RXID                     0x07DF

#define FLASH_SIZE                           0x2000
#define FBL_WD_TRIGGER_SIZE                  1024
#define FBL_WDTRIGGER_EXTRA_WORDS            128
/* FBL Ford specific */
#define FBL_DISABLE_USERSUBFUNCTION
#define FBL_DISABLE_USERSERVICE
#define FBL_DISABLE_USERROUTINE
/* Data Processing */
#ifdef FBL_ENABLE_COMPRESSION_MODE
#define FBL_ENABLE_PROCESSED_DATA_LENGTH
#else
#define FBL_DISABLE_PROCESSED_DATA_LENGTH
#endif

#define FBL_ENABLE_FBL_START
#define FBL_ENABLE_UPLOAD
#define FBL_DISABLE_EXCEEDED_RETRIES_REJECT
#define FBL_DISABLE_SEED_KEY_MODULE
#define SWM_DATA_MAX_NOAR                    8
/* PBL Configuration */
#define FBL_DISABLE_WRITE_DATA_BY_IDENTIFIER
#define FBL_DISABLE_CAN_CONFIGURATION
#define CAN_CONFIG_TABLE_ADDR                0x00
/* Multiple nodes support */
#define FBL_DISABLE_MULTIPLE_NODES
/* Download Validation */
#define FBL_DISABLE_ENHANCED_VALIDATION
#define FBL_MASK_PATTERN_ADDR                0x018000
#define FBL_MASK_PATTERN_SIZE                0x08
#define FBL_MASK_PATTERN_VALID               {0x5A, 0xF0, 0xA5, 0x0F, 0x11, 0x22, 0x33, 0x44}
#define FBL_DISABLE_USER_CHECKSUM
/* Validation Structure */
#define FBL_ENABLE_VALSTRUCT
#define FBL_VALSTRUCT_ADDR                   0x02001C
#define FBL_VALSTRUCT_TAGBEGIN_PATTERN       0x74EBE612
#define FBL_VALSTRUCT_TAGEND_PATTERN         0xF12A1E2D
/* Flash Erased Detection */
#define FBL_DISABLE_FLASH_ERASED_DETECTION
#define FBL_FLASH_ERASED_PATTERN_ADDR        0x00
#define FBL_FLASH_ERASED_PATTERN_SIZE        0x10


/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

/* User Config File ********************************************************** */
/* User Section ************************************************************** */
/* Diagnostic options */
#define FBL_ENABLE_DIAG_SESSION_PARAMETERS
#define FBL_ENABLE_FIXED_TRANSFER_ALFI
#define FBL_DIAG_DISABLE_ENUMS_IDX
#define FBL_ENABLE_UNALIGNED_DATA_TRANSFER

/* Workaround for new encryption mode handling */
#define FBL_DISABLE_ENCRYPTION_MODE
/* *************************************************************************** */


/* begin Fileversion check */
#ifndef SKIP_MAGIC_NUMBER
#ifdef MAGIC_NUMBER
  #if MAGIC_NUMBER != 128388395
      #error "The magic number of the generated file <C:\Synergy\ES_EPS_EA3_FBL_FORD-Haitec\ES_EPS_EA3_FBL_FORD\SwProject\GENy_files\fbl_cfg.h> is different. Please check time and date of generated files!"
  #endif
#else
  #define MAGIC_NUMBER 128388395
#endif  /* MAGIC_NUMBER */
#endif  /* SKIP_MAGIC_NUMBER */

/* end Fileversion check */

#endif /* __FBL_CFG_H__ */
