/* -----------------------------------------------------------------------------
  Filename:    CanIf_Lcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: CanIf
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-04-17  11:15:35
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define CANIF_LCFG_SOURCE

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanLinktimeCRC */
#include "CanIf_Cfg.h"
#include "Can_Cfg.h"
/* END of Checksum exclude for
  - If_AsrIfCanLinktimeCRC */


#define CANIF_START_SEC_APPL_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Prototypes for Callback functions
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Tx Confirmation Functions
 ----------------------------------------------------------------------------- */

FUNC(void, CANIF_APPL_CODE) PduR_CanIfTxConfirmation(PduIdType CanTxPduId);
FUNC(void, CANIF_APPL_CODE) CanTp_TxConfirmation(PduIdType CanTxPduId);
FUNC(void, CANIF_APPL_CODE) CanXcp_TxConfirmation(PduIdType CanTxPduId);
FUNC(void, CANIF_APPL_CODE) SrlComOutput_TxNM(PduIdType CanTxPduId);


/* -----------------------------------------------------------------------------
    &&&~ Rx Indication Functions
 ----------------------------------------------------------------------------- */

FUNC(void, CANIF_APPL_CODE) PduR_CanIfRxIndication(PduIdType CanRxPduId, P2CONST(uint8, AUTOMATIC, CANIF_APPL_VAR) CanSduPtr);
FUNC(void, CANIF_APPL_CODE) CanTp_RxIndication(PduIdType CanRxPduId, P2CONST(PduInfoType, AUTOMATIC, CANIF_APPL_VAR) PduInfoPtr);
FUNC(void, CANIF_APPL_CODE) CanXcp_RxIndication(PduIdType CanRxPduId, P2CONST(PduInfoType, AUTOMATIC, CANIF_APPL_VAR) PduInfoPtr);
FUNC(void, CANIF_APPL_CODE) GliwaT1_MsgProcess_RxT1HostToTarget(PduIdType CanRxPduId, P2CONST(uint8, AUTOMATIC, CANIF_APPL_VAR) CanSduPtr);
FUNC(void, CANIF_APPL_CODE) SrlComOutput_RxNM(PduIdType CanRxPduId, P2CONST(uint8, AUTOMATIC, CANIF_APPL_VAR) CanSduPtr);


/* -----------------------------------------------------------------------------
    &&&~ BusOff Indication Functions
 ----------------------------------------------------------------------------- */

FUNC(void, CANIF_APPL_CODE) CanSM_ControllerBusOff(uint8 Controller);


/* -----------------------------------------------------------------------------
    &&&~ WakeupEvent Functions
 ----------------------------------------------------------------------------- */

#ifndef ECUM_SET_WAKEUP_EVENT_DECLARATION
FUNC(void, CANIF_APPL_CODE) EcuM_SetWakeupEvent(EcuM_WakeupSourceType CanWakeupEvents);
#define ECUM_SET_WAKEUP_EVENT_DECLARATION
#endif



/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */


#define CANIF_STOP_SEC_APPL_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ variable declaration (initialized)
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
VAR(CanIf_ControllerModeType, CANIF_VAR_ZERO_INIT) CanIf_ControllerMode[CANIF_MAX_CONTROLLER_TABLESIZE] = 
{
  CANIF_CS_UNINIT
};
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */


#define CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ variable declaration
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
VAR(CanIf_PduGetModeType, CANIF_VAR_NOINIT) CanIf_ChannelMode[CANIF_MAX_CONTROLLER_TABLESIZE];
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */


#define CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Callback function tables
 ----------------------------------------------------------------------------- */

CONST(CanIf_TxConfirmationFctType, CANIF_CONST) CanIf_TxConfirmationFctList[CANIF_MAX_TXCONFIRMATION_LIST] = 
{
  NULL_PTR, 
  PduR_CanIfTxConfirmation, 
  CanTp_TxConfirmation, 
  CanXcp_TxConfirmation, 
  SrlComOutput_TxNM
};
CONST(CanIf_RxIndicationFctStructType, CANIF_CONST) CanIf_RxIndicationFctList[CANIF_MAX_RXINDICATION_LIST] = 
{
  { { NULL_PTR }, CanIf_SimpleRxIndicationLayout }, 
  { { (CanIf_SimpleRxIndicationFctType) PduR_CanIfRxIndication }, CanIf_SimpleRxIndicationLayout }, 
  { { (CanIf_SimpleRxIndicationFctType) CanTp_RxIndication }, CanIf_AdvancedRxIndicationLayout }, 
  { { (CanIf_SimpleRxIndicationFctType) CanXcp_RxIndication }, CanIf_AdvancedRxIndicationLayout }, 
  { { (CanIf_SimpleRxIndicationFctType) GliwaT1_MsgProcess_RxT1HostToTarget }, CanIf_SimpleRxIndicationLayout }, 
  { { (CanIf_SimpleRxIndicationFctType) SrlComOutput_RxNM }, CanIf_SimpleRxIndicationLayout }
};


/* -----------------------------------------------------------------------------
    &&&~ BusOffIndicationFct
 ----------------------------------------------------------------------------- */

CONST(CanIf_BusOffNotificationFctType, CANIF_CONST) CanIf_BusOffNotificationFct = CanSM_ControllerBusOff;


/* -----------------------------------------------------------------------------
    &&&~ WakeUpEventFct
 ----------------------------------------------------------------------------- */

CONST(CanIf_WakeUpEventFctType, CANIF_CONST) CanIf_WakeUpEventFct = EcuM_SetWakeupEvent;


/* -----------------------------------------------------------------------------
    &&&~ DEM Error Handling
 ----------------------------------------------------------------------------- */

CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_SleepReqFailed = CANIF_E_INVALID_DLC;
CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_InvalidDlc = CANIF_E_INVALID_DLC;
CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_Stopped = CANIF_E_STOPPED;
CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_TxBufferFull = CANIF_E_FULL_TX_BUFFER;


/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */

#define CANIF_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Postbuild configuration
 ----------------------------------------------------------------------------- */

CONST(CanIf_ConfigType, CANIF_PBCFG_ROOT) CanIf_Config = 
{
  0x031405 /* Generator version */, 
  CanIf_ControllerConfig /* Controller config pointer */, 
  CanIf_RxPduConfig /* RxPdu config pointer */, 
  CanIf_RxPduId /* RxPduId table pointer */, 
  CanIf_RxPduMask /* RxPduMask table pointer */, 
  CanIf_TxPduConfig /* Tx Pdu config pointer */, 
  (CanIf_PduIdPtrType) 0 /* TxQueue config pointer */, 
  CanIf_MailBoxConfig /* Mailbox config pointer */, 
  CanIf_WakeUpConfig /* Wakeup config pointer */, 
  (CanIf_TransceiverMapPtrType) 0 /* Transceiver mapping table pointer */, 
  (CanIf_PduIdPtrType) 0 /* NPB conversion table pointer */, 
  CanControllerConfig /* CanControllerConfig pointer */, 
  CanIf_MagicNumber /* MagicNumber pointer */, 
  8 /* Number of Rx PDUs + Ranges */, 
  6 /* Number of Tx PDUs */, 
  0 /* Number of NPB Tx messages */, 
  1 /* Number of channels */, 
  17 /* Number of CAN Hw objects */, 
  5 /* Number of Tx Confirmation functions */, 
  6 /* Number of Rx Confirmation functions */, 
  0 /* MaxNrOfWakeupSources */, 
  0 /* MaxNrOfTransceiver */, 
  0x0600 /* Generator compatibility version */, 
  0xDEAF
};



#define CANIF_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Postbuild configuration
 ----------------------------------------------------------------------------- */

CONST(CanIf_ControllerConfigType, CANIF_PBCFG) CanIf_ControllerConfig[CANIF_MAX_CONTROLLER] = 
{
  
  {
    0 /* TxBCStartIndex */, 
    0 /* TxBCStopIndex */
  }
};
CONST(CanIf_RxPduConfigType, CANIF_PBCFG) CanIf_RxPduConfig[CANIF_MAX_RXPDUHANDLE] = 
{
  
  {
    0 /* UpperLayer PduID - PduId(Index): 0 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 4 /* GliwaT1_MsgProcess_RxT1HostToTarget */
  }, 
  
  {
    0 /* UpperLayer PduID - PduId(Index): 1 */, 
    8 /* Data Length Code NOT optimized */, /* NXTR MANUAL EDIT */
    (uint8) 2 /* CanTp_RxIndication */
  }, 
  
  {
    1 /* UpperLayer PduID - PduId(Index): 2 */, 
    8 /* Data Length Code NOT optimized */, /* NXTR MANUAL EDIT */
    (uint8) 2 /* CanTp_RxIndication */
  }, 
  
  {
    0 /* UpperLayer PduID - PduId(Index): 3 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 5 /* SrlComOutput_RxNM */
  }, 
  
  {
    0 /* UpperLayer PduID - PduId(Index): 4 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 3 /* CanXcp_RxIndication */
  }, 
  
  {
    0 /* UpperLayer PduID - PduId(Index): 5 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 1 /* PduR_CanIfRxIndication */
  }, 
  
  {
    1 /* UpperLayer PduID - PduId(Index): 6 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 1 /* PduR_CanIfRxIndication */
  }, 
  
  {
    2 /* UpperLayer PduID - PduId(Index): 7 */, 
    8 /* Data Length Code NOT optimized */, 
    (uint8) 1 /* PduR_CanIfRxIndication */
  }
};
CONST(Can_IdType, CANIF_PBCFG) CanIf_RxPduId[CANIF_MAX_RXPDUHANDLE] = 
{
  0x07F0 /* GliwaMaster__CAN00 CanId: 0x7f0 (Index: 0) */, 
  0x07D0 /* DiagFuncReqFT_Tp__CAN00 CanId: 0x7d0 (Index: 1) */, 
  0x0772 /* DiagPhysReqToEPAS_Tp__CAN00 CanId: 0x772 (Index: 2) */, 
  0x0700 /* NMmBCM__CAN00 CanId: 0x700 (Index: 3) */, 
  0x0695 /* XcpMaster__CAN00 CanId: 0x695 (Index: 4) */, 
  0x0420 /* BCM1__CAN00 CanId: 0x420 (Index: 5) */, 
  0x0360 /* ABS2__CAN00 CanId: 0x360 (Index: 6) */, 
  0x0316 /* ECM1__CAN00 CanId: 0x316 (Index: 7) */
};
CONST(Can_IdType, CANIF_PBCFG) CanIf_RxPduMask[CANIF_MAX_RXPDUHANDLE] = 
{
  0x47FF /* GliwaMaster__CAN00 (Index: 0) */, 
  0x47FF /* DiagFuncReqFT_Tp__CAN00 (Index: 1) */, 
  0x47FF /* DiagPhysReqToEPAS_Tp__CAN00 (Index: 2) */, 
  0x47FF /* NMmBCM__CAN00 (Index: 3) */, 
  0x47FF /* XcpMaster__CAN00 (Index: 4) */, 
  0x47FF /* BCM1__CAN00 (Index: 5) */, 
  0x47FF /* ABS2__CAN00 (Index: 6) */, 
  0x47FF /* ECM1__CAN00 (Index: 7) */
};
CONST(CanIf_TxPduConfigType, CANIF_PBCFG) CanIf_TxPduConfig[CANIF_MAX_TXPDUHANDLE] = 
{
  
  {
    0x07F1 /* CanId: 0x7f1 (PduId/Index: 0) */, 
    0 /* Controller */, 
    5 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 0 /* NULL_PTR */
  }, 
  
  {
    0x07B2 /* CanId: 0x7b2 (PduId/Index: 1) */, 
    0 /* Controller */, 
    4 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 2 /* CanTp_TxConfirmation */
  }, 
  
  {
    0x0707 /* CanId: 0x707 (PduId/Index: 2) */, 
    0 /* Controller */, 
    3 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 4 /* SrlComOutput_TxNM */
  }, 
  
  {
    0x06E5 /* CanId: 0x6e5 (PduId/Index: 3) */, 
    0 /* Controller */, 
    2 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 3 /* CanXcp_TxConfirmation */
  }, 
  
  {
    0x039E /* CanId: 0x39e (PduId/Index: 4) */, 
    0 /* Controller */, 
    1 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 1 /* PduR_CanIfTxConfirmation */
  }, 
  
  {
    0x039A /* CanId: 0x39a (PduId/Index: 5) */, 
    0 /* Controller */, 
    0 /* Hardware Transmit Handle */, 
    8 /* Data Length Code */, 
    (uint8) 1 /* PduR_CanIfTxConfirmation */
  }
};

CONST(CanIf_MailBoxConfigType, CANIF_PBCFG) CanIf_MailBoxConfig[CANIF_MAX_MAILBOX] = 
{
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 3 /* CANIF_TxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused for Tx message objects */, 
    0 /* Unused for Tx message objects */, 
    (CanIf_MailBoxTypeType) 2 /* CANIF_TxBasicCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* Unused object */, 
    0 /* Unused object */, 
    (CanIf_MailBoxTypeType) 4 /* CANIF_UnusedCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    54 /* RxPduIdIndex (First) */, 
    0 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    55 /* RxPduIdIndex (First) */, 
    1 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    56 /* RxPduIdIndex (First) */, 
    2 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    57 /* RxPduIdIndex (First) */, 
    3 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    58 /* RxPduIdIndex (First) */, 
    4 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    59 /* RxPduIdIndex (First) */, 
    5 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    60 /* RxPduIdIndex (First) */, 
    6 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    61 /* RxPduIdIndex (First) */, 
    7 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 1 /* CANIF_RxFullCANMailbox */, 
    0 /* Controller */
  }, 
  
  {
    0 /* RxPduIdIndex (First) */, 
    0 /* RxPduIdIndex (Last) */, 
    (CanIf_MailBoxTypeType) 0 /* CANIF_RxBasicCANMailbox */, 
    0 /* Controller */
  }
};

CONST(CanIf_WakeUpConfigType, CANIF_PBCFG) CanIf_WakeUpConfig[CANIF_MAX_WAKEUPSOURCES] = 
{
  
  {
    0 /* Wakeup Source */, 
    (CanIf_WakeUpTargetType) 0 /* CANIF_WAKEUPREQUEST_NONE */, 
    0 /* Target Index (Controller/TrcvIndex) */, 
    0 /* Controller */
  }
};

CONST(uint16, CANIF_PBCFG) CanIf_MagicNumber[1] = 
{
  0xDEAF
};


#define CANIF_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define CANIF_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



