/* -----------------------------------------------------------------------------
  Filename:    CanIf_Cfg.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: CanIf
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-04-17  11:15:35
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(CANIF_CFG_H)
#define CANIF_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
#include "ComStack_Types.h"
#include "Dem.h"
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ VersionDefines
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
#define CANIFDLL_VERSION                     0x0314
#define CANIFDLL_RELEASE_VERSION             0x05
#define IF_ASRIFCAN_GENTOOL_GENY_MAJOR_VERSION 0x03
#define IF_ASRIFCAN_GENTOOL_GENY_MINOR_VERSION 0x14
#define IF_ASRIFCAN_GENTOOL_GENY_PATCH_VERSION 0x05
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
#define CANIF_TRANSMIT_BUFFER STD_OFF
#define CANIF_BITQUEUE STD_OFF
#define CANIF_READRXPDUDATA_API STD_OFF
#define CANIF_LIBRARY_SUPPORT STD_ON
#define CANIF_WAKEUP_SUPPORT STD_ON
#define CANIF_WAKEUP_VALIDATION STD_OFF
#define CANIF_DEV_ERROR_DETECT STD_ON
#define CANIF_PROD_ERROR_DETECT STD_ON
#define CANIF_TRANSMIT_CANCELLATION STD_OFF
#define CANIF_CANCEL_SUPPORT_API STD_ON
#define CANIF_VERSION_INFO_API STD_ON
#define CANIF_DLC_CHECK STD_ON
#define CANIF_SUPPORT_NMOSEK_INDICATION STD_OFF
#define CANIF_SUPPORT_NONPB_API STD_OFF
#define CANIF_TRCV_HANDLING STD_OFF
#define CANIF_TRCV_MAPPING STD_OFF
#define CANIF_BUSOFF_RECOVERY_API STD_OFF
#define CANIF_EXTENDED_STATE_MACHINE STD_OFF
#define CANIF_EXTENDEDID_SUPPORT STD_OFF
#define CANIF_COMPATIBILITY_AUTOSAR21 STD_OFF
#define CANIF_TRCV_WAKEUPSTATETRANSITION STD_ON
#define CANIF_DEMTODET_E_STOPPED STD_OFF
#define CANIF_DEMTODET_E_FULL_TX_BUFFER STD_OFF
#define CANIF_DEM_REPORT_DLC_FAILED STD_ON
#define CANIF_USER_DLC_ERROR_NOTIFICATION STD_OFF
#define CANIF_WAKEUP_VALID_ALL_RX_MSGS STD_ON
#define CANIF_ENABLE_TX_LPDU_REMAPPING STD_OFF
#define CANIF_ONE_CONTROLLER_OPTIMIZATION STD_OFF
#define CANIF_SETDYNAMICTXID_API STD_OFF
#define CANIF_PARTIAL_NETWORK STD_OFF
/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tablesize Definition
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
#define CANIF_MAX_CONTROLLER                 1
#define CANIF_MAX_RXPDUHANDLE                8
#define CANIF_MAX_TXPDUHANDLE                6
#define CANIF_MAX_MAILBOX                    17
#define CANIF_MAX_WAKEUPSOURCES              1
#define CANIF_MAX_TRANSCEIVER                1
#define CANIF_MAX_MAPPEDTXPDUS               1
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
#define CANIF_MAX_CONTROLLER_TABLESIZE       CANIF_MAX_CONTROLLER
#define CANIF_MAX_TXPDUHANDLE_TABLESIZE      CANIF_MAX_TXPDUHANDLE
#define CANIF_MAX_NORMALTXPDUHANDLE_TABLESIZE 1
#define CANIF_MAX_TXQUEUESIZE                0
#define CANIF_MAX_TXCONFIRMATION_LIST        5
#define CANIF_MAX_RXINDICATION_LIST          6
#define CANIF_MAX_TRANSCEIVERDRIVERS         1
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */



/* -----------------------------------------------------------------------------
    &&&~ Search Algorithm
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
#define CANIF_SEARCH_ALGORITHM               CANIF_LINEAR
/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Configuration Variant
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
#define CANIF_CONFIG_VARIANT                 1
/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Dem compatibility code
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
#if (CANIF_PROD_ERROR_DETECT == STD_ON)
#ifndef CANIF_E_FULL_TX_BUFFER
#define CANIF_E_FULL_TX_BUFFER               Dem_CANIF_E_FULL_TX_BUFFER
#endif

#ifndef CANIF_E_STOPPED
#define CANIF_E_STOPPED                      Dem_CANIF_E_STOPPED
#endif

#ifndef CANIF_E_INVALID_DLC
#define CANIF_E_INVALID_DLC                  Dem_CANIF_E_INVALID_DLC
#endif

#ifndef CANIF_E_SLEEP_REQ_FAILED
#define CANIF_E_SLEEP_REQ_FAILED             Dem_CANIF_E_SLEEP_REQ_FAILED
#endif

#endif

/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */



/* -----------------------------------------------------------------------------
    &&&~ TxBufferApi
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
#define CanIf_CanIfPrivateConfiguration      None
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Multiple Configuration Container forwarding to Init Struct
 ----------------------------------------------------------------------------- */

#define CanIfInitConfiguration               CanIf_Config


/* -----------------------------------------------------------------------------
    &&&~ Linktime / Precompile CRC
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
#define CANIF_CRC_CHECK                      STD_OFF
#define CANIF_PRECOMPILE_CRC                 (uint32) 0xDCF7AD8D
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

#include "CanIf_Types.h"


/* -----------------------------------------------------------------------------
    &&&~ externals
 ----------------------------------------------------------------------------- */

#define CANIF_START_SEC_VAR_ZERO_INIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
extern VAR(CanIf_ControllerModeType, CANIF_VAR_ZERO_INIT) CanIf_ControllerMode[CANIF_MAX_CONTROLLER_TABLESIZE];
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */

#define CANIF_STOP_SEC_VAR_ZERO_INIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
extern VAR(CanIf_PduGetModeType, CANIF_VAR_NOINIT) CanIf_ChannelMode[CANIF_MAX_CONTROLLER_TABLESIZE];
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */

#define CANIF_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Extern Decl Callback function tables
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
extern CONST(CanIf_BusOffNotificationFctType, CANIF_CONST) CanIf_BusOffNotificationFct;
extern CONST(CanIf_WakeUpEventFctType, CANIF_CONST) CanIf_WakeUpEventFct;
/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */

/* START of Checksum include for
  - If_AsrIfCanLinktimeCRC */
extern CONST(CanIf_TxConfirmationFctType, CANIF_CONST) CanIf_TxConfirmationFctList[CANIF_MAX_TXCONFIRMATION_LIST];
extern CONST(CanIf_RxIndicationFctStructType, CANIF_CONST) CanIf_RxIndicationFctList[CANIF_MAX_RXINDICATION_LIST];
/* END of Checksum include for
  - If_AsrIfCanLinktimeCRC */



/* -----------------------------------------------------------------------------
    &&&~ DEM Error Handling
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - If_AsrIfCanPrecompileCRC */
extern CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_SleepReqFailed;
extern CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_InvalidDlc;
extern CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_Stopped;
extern CONST(Dem_EventIdType, CANIF_CONST) CanIf_DemError_TxBufferFull;
/* END of Checksum include for
  - If_AsrIfCanPrecompileCRC */



#define CANIF_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
extern CONST(CanIf_ConfigType, CANIF_PBCFG_ROOT) CanIf_Config;
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */

#define CANIF_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */
extern CONST(CanIf_ControllerConfigType, CANIF_PBCFG) CanIf_ControllerConfig[CANIF_MAX_CONTROLLER];
extern CONST(CanIf_RxPduConfigType, CANIF_PBCFG) CanIf_RxPduConfig[CANIF_MAX_RXPDUHANDLE];
extern CONST(Can_IdType, CANIF_PBCFG) CanIf_RxPduId[CANIF_MAX_RXPDUHANDLE];
extern CONST(Can_IdType, CANIF_PBCFG) CanIf_RxPduMask[CANIF_MAX_RXPDUHANDLE];
extern CONST(CanIf_TxPduConfigType, CANIF_PBCFG) CanIf_TxPduConfig[CANIF_MAX_TXPDUHANDLE];
extern CONST(CanIf_MailBoxConfigType, CANIF_PBCFG) CanIf_MailBoxConfig[CANIF_MAX_MAILBOX];
extern CONST(uint16, CANIF_PBCFG) CanIf_MagicNumber[1];
extern CONST(CanIf_WakeUpConfigType, CANIF_PBCFG) CanIf_WakeUpConfig[CANIF_MAX_WAKEUPSOURCES];
/* END of Checksum exclude for
  - If_AsrIfCanPrecompileCRC */

#define CANIF_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANIF_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define CANIF_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"





#endif /* CANIF_CFG_H */
