/* -----------------------------------------------------------------------------
  Filename:    CanSM_Lcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: CanSM
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-10-16  09:18:18
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#include "CanXcp.h"
#include "CanSM_EcuM.h"
#include "Vmm_BusSM.h"
#define CANSM_START_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
CONST(uint8, CANSM_CONST) CanSMCountOfCanNetworks = 1u;
CONST(uint8, CANSM_CONST) CanSMNwSmMaxRepetitions = 5u;
CONST(uint8, CANSM_CONST) CanSMNetworkHandle[1] = 
{
  0u
};
CONST(uint8, CANSM_CONST) CanSMControllerId[1] = 
{
  0u
};
CONST(uint8, CANSM_CONST) CanSMTransceiverId[1] = 
{
  0u
};
CONST(boolean, CANSM_CONST) CanSMNetworkTransceiverHandling[1] = 
{
  FALSE
};
CONST(boolean, CANSM_CONST) CanSMBusOffRxDM[1] = 
{
  FALSE
};
/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
CONST(Com_PduGroupIdType, CANSM_CONST) CanSMRxPduGroupId[1] = 
{
  PduGrp_EPAS__CAN00_Rx
};
CONST(Com_PduGroupIdType, CANSM_CONST) CanSMTxPduGroupId[1] = 
{
  PduGrp_EPAS__CAN00_Tx
};
/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

#define CANSM_STOP_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#if (CANSM_CRC_CHECK == STD_ON)
#define CANSM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, CANSM_CONST) CanSM_LinktimeCRC = (uint32) 0x6E9ED02Cu;
#define CANSM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#endif

#define CANSM_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(CanSM_ConfigType, CANSM_PBCFG) CanSMConfiguration = 
{
  CanSMBorTimeTxEnsured, 
  CanSMBorTimeL1, 
  CanSMBorTimeL2, 
  CanSMBorCounterL1ToL2, 
  CanSMBorCounterL2Err, 
  0x011704u
};

#define CANSM_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANSM_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeTxEnsured
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeTxEnsured[1] = 
{
  1000u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeL1
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeL1[1] = 
{
  500u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorTimeL2
 ----------------------------------------------------------------------------- */

CONST(uint16, CANSM_PBCFG) CanSMBorTimeL2[1] = 
{
  500u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorCounterL1ToL2
 ----------------------------------------------------------------------------- */

CONST(uint8, CANSM_PBCFG) CanSMBorCounterL1ToL2[1] = 
{
  1u
};


/* -----------------------------------------------------------------------------
    &&&~ CanSMBorCounterL2Err
 ----------------------------------------------------------------------------- */

CONST(uint8, CANSM_PBCFG) CanSMBorCounterL2Err[1] = 
{
  2u
};



#define CANSM_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define CANSM_START_SEC_VAR_ZERO_INIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
VAR(uint8, CANSM_VAR_ZERO_INIT) CanSM_EnableSetBusSleep[1] = 
{
  0
};
/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

#define CANSM_STOP_SEC_VAR_ZERO_INIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define CANSM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
VAR(CanSM_LocalClusterDataType, CANSM_VAR_NOINIT) CanSM_ClusterState[1];
/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

#define CANSM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define CANSM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
FUNC(void, CANSM_CODE) CanSm_SwitchIpduGroup(uint8 CanSm_CanNetworkIdx, uint8 RxTxStartStop)
{
  switch(CanSm_CanNetworkIdx)
  {
    case 0:
    {
      switch(RxTxStartStop)
      {
        case CANSM_PDU_RX_START:
        {
          Vmm_BusSm_IpduGroupStart(0, PduGrp_EPAS__CAN00_Rx, FALSE);
          break;
        }
        case CANSM_PDU_TX_START:
        {
          Vmm_BusSm_IpduGroupStart(0, PduGrp_EPAS__CAN00_Tx, FALSE);
          break;
        }
        case CANSM_PDU_RX_STOP:
        {
          Vmm_BusSm_IpduGroupStop(0, PduGrp_EPAS__CAN00_Rx);
          break;
        }
        case CANSM_PDU_TX_STOP:
        {
          Vmm_BusSm_IpduGroupStop(0, PduGrp_EPAS__CAN00_Tx);
          break;
        }
        default:
        {
          break;
        }
      }
      break;
    }
    default:
    {
      break;
    }
  }
}


/* -----------------------------------------------------------------------------
    &&&~ Postbuild configuration
 ----------------------------------------------------------------------------- */

FUNC(void, CANSM_CODE) CanSM_Xcp_SetPduMode(uint8 CanSm_CanNetworkIdx, uint8 OnOffLine)
{
  if(0 == CanSm_CanNetworkIdx)
  {
    CanXcp_SetPduMode(0, (CanXcp_PduSetModeType) OnOffLine);
  }
}




/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

/* START of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */
FUNC(void, CANSM_CODE) CanSm_Dem_ReportErrorEvent(uint8 CanSm_CanNetworkIdx, uint8 CanSm_EventId, Dem_EventStatusType CanSm_EventStatus)
{
  switch(CanSm_CanNetworkIdx)
  {
    case 0:
    {
      if(CanSm_EventId == 0)
      {
        (void)Dem_ReportErrorStatus( CANSM_E_MODE_CHANGE_NETWORK_0, CanSm_EventStatus );
      }
      else
      {
        if(CanSm_EventId == 1)
        {
          (void)Dem_ReportErrorStatus( CANSM_E_BUSOFF_NETWORK_0, CanSm_EventStatus );
        }
      }
      break;
    }
    default:
    {
      break;
    }
  }
}


/* END of Checksum include for
  - Ccl_AsrSmCanLinktimeCRC */

#define CANSM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


