/* -----------------------------------------------------------------------------
  Filename:    CanTp_Cfg.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: CanTp
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-04-16  10:42:35
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(CANTP_CFG_H)
#define CANTP_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Include files
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */
#include "CanTp_Types.h"
/* END of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ DET error handles
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */
#define CANTP_E_OPER_NOT_SUPPORTED           0xA0u
/* END of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Global defines
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */
/* Definition of feature switches in the library delivered */
#define CANTP_NO_CHANNELS                    1
#define CANTP_USE_DUMMY_STATEMENT            STD_ON
/* END of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */


/* START of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */
#define CANTP_VERSION_INFO_API               STD_ON
#define CANTP_AUTOSARVERSION3                STD_ON
#define CANTP_DEV_ERROR_DETECT               STD_ON
#define CANTP_PROD_ERROR_DETECT              STD_ON
#define CANTP_HAVE_INIT_CFG_PTR              STD_OFF
#define CANTP_TC                             STD_OFF
#define CANTP_TC_NOTIFY_ALWAYS               STD_OFF
#define CANTP_RC                             STD_OFF
#define CANTP_RC_NOTIFY_ALWAYS               STD_OFF
#define CANTP_CONFIG_VARIANT                 1
#define CANTP_ENABLE_INDICATION              STD_ON
#define CANTP_ENABLE_CONFIRMATION            STD_ON
#define CANTP_DCM_REQUEST_DETECT             STD_OFF
#define CANTP_IDENTITY_MANAGER_CONFIG        STD_OFF
#define CANTP_OPER_NOT_SUPPORTED_REPORT_DEM  STD_OFF
#define CANTP_E_COMM_REPORT_DEM              STD_ON
#define CANTP_INVALID_HDL                    ((PduIdType) 0xFFFFu)
/* END of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Vector-CanTp extended capabilities
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */
/* Extended error detection capabilities */
#define CANTP_HAVE_EXT_DEV_ERROR_DETECT      STD_OFF
#define CANTP_CRC_CHECK                      STD_OFF
#define CANTP_PRECOMPILE_CRC                 (uint32) 0x25DBBF56u
#define CANTP_HAVE_MULTI_PURPOSE_TP          STD_OFF
#define CANTP_PADDING_ACTIVE                 STD_ON
#define CANTP_HAVE_PADDING_BYTE              STD_ON
/* Padding byte to be used for the Tx side if CANTP_HAVE_PADDING_BYTE is ON */
#define CANTP_PADDING_PATTERN                0x00u
#define CANTP_RAM_OPTIMIZED                  STD_OFF
#define CANTP_STANDARD_ADDRESSING            STD_ON
#define CANTP_EXTENDED_ADDRESSING            STD_ON
#define CANTP_MIXED11_ADDRESSING             STD_OFF
#define CANTP_RX_FULL_BUFFER_PROVISION       STD_ON
#define CANTP_TX_FULL_BUFFER_PROVISION       STD_ON
#define CANTP_SINGLE_CONN_OPTIMIZED          STD_OFF
#define CANTP_SINGLE_CONN_NOPB_OPTIMIZED     STD_OFF
#define CANTP_RXTX_MAINFUNCTION_API          STD_OFF
#define CANTP_ENABLE_RX_NSDU_REMAPPING       STD_OFF
#define CANTP_ENABLE_TX_NSDU_REMAPPING       STD_OFF
#define CANTP_ENABLE_WRAP_TRANSMIT           STD_OFF
#define CANTP_ENABLE_WRAP_CANCEL_TRANSMIT    STD_OFF
#define CANTP_ENABLE_EXT_API_BS              STD_OFF
#define CANTP_ENABLE_EXT_API_STMIN           STD_OFF
#define CANTP_CONSTANT_BS                    STD_OFF
#define CANTP_IGNORE_FC_WITH_RES_STMIN       STD_OFF
#define CANTP_REJECT_FC_WITH_RES_STMIN       STD_OFF
#define CANTP_IGNORE_FC_OVFL_INVALID_FS      STD_OFF
#define CANTP_IGNORE_CF_WITH_WRONG_SN        STD_OFF
#define CANTP_USE_ONLY_FIRST_FC              STD_OFF
#define CANTP_ENABLE_CHANGE_PARAM            STD_OFF
#define CANTP_ENABLE_PDUR_SOR                STD_OFF
#define CANTP_FF_PROVIDE_2_RXBUFFER_CALLS    STD_OFF
#define CANTP_SUPPRESS_PREPASS_INDICATION    STD_OFF
#define CANTP_STRICT_RX_CALL_SEQ             STD_OFF
#define CANTP_ASYNC_TRANSMIT                 STD_OFF
/* END of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Pre-Compile optimized configuration
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */
#define CANTP_CONSTANT_RX__DL                STD_ON
#define CANTP_RX__DL                         8
#define CANTP_CONSTANT_RX__NAR               STD_ON
#define CANTP_RX__NAR                        4
#define CANTP_CONSTANT_RX__NBR               STD_ON
#define CANTP_RX__NBR                        2
#define CANTP_CONSTANT_RX__NCR               STD_ON
#define CANTP_RX__NCR                        16
#define CANTP_CONSTANT_RX__WFTMAX            STD_ON
#define CANTP_RX__WFTMAX                     0
#define CANTP_CONSTANT_RX__PADDING_ACTIVATION STD_ON
#define CANTP_RX__PADDING_ACTIVATION         1
#define CANTP_CONSTANT_RX__TA_TYPE           STD_OFF
#define CANTP_CONSTANT_RX__ADDRESSING_FORMAT STD_ON
#define CANTP_RX__ADDRESSING_FORMAT          0
#define CANTP_CONSTANT_RX__MAX_PAYLOAD_LENGTH STD_ON
#define CANTP_RX__MAX_PAYLOAD_LENGTH         7
#define CANTP_CONSTANT_RX__BS                STD_ON
#define CANTP_RX__BS                         0
#define CANTP_CONSTANT_RX__STMIN             STD_ON
#define CANTP_RX__STMIN                      20
#define CANTP_CONSTANT_TX__DL                STD_ON
#define CANTP_TX__DL                         8
#define CANTP_CONSTANT_TX__NAS               STD_ON
#define CANTP_TX__NAS                        4
#define CANTP_CONSTANT_TX__NBS               STD_ON
#define CANTP_TX__NBS                        9
#define CANTP_CONSTANT_TX__NCS               STD_ON
#define CANTP_TX__NCS                        2
#define CANTP_CONSTANT_TX__PADDING_ACTIVATION STD_ON
#define CANTP_TX__PADDING_ACTIVATION         1
#define CANTP_CONSTANT_TX__TA_TYPE           STD_ON
#define CANTP_TX__TA_TYPE                    0
#define CANTP_CONSTANT_TX__ADDRESSING_FORMAT STD_ON
#define CANTP_TX__ADDRESSING_FORMAT          0
#define CANTP_CONSTANT_TX__MAX_PAYLOAD_LENGTH STD_ON
#define CANTP_TX__MAX_PAYLOAD_LENGTH         7
#define CANTP_CONSTANT_TX__TC                STD_ON
#define CANTP_TX__TC                         1
/* END of Checksum include for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Pdu IDs
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */
#define DiagFuncReqFT__CAN00                 0
#define DiagPhysReqToEPAS__CAN00_EPAS        1
/* END of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Pdu IDs
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */
#define DiagRespFromEPAS__CAN00              0
/* END of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ CanIf RxPdu Handles
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */
#define CanTp_DiagFuncReqFT_Tp__CAN00        0
#define CanTp_DiagPhysReqToEPAS_Tp__CAN00    1
/* END of Checksum exclude for
  - Tp_AsrTpCanPrecompileCRC */



#endif /* CANTP_CFG_H */
