/* -----------------------------------------------------------------------------
  Filename:    CanXcp_PBcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: CanXcp
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-02-13  10:21:39
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ 
 ----------------------------------------------------------------------------- */

#include "CanXcp_Cfg.h"

/* -----------------------------------------------------------------------------
    &&&~ Postbuild Configuration
 ----------------------------------------------------------------------------- */

/* PRQA S 5087 5 */ /* MISRA rule 19.1 violation due to AUTOSAR requirement for Memory Mapping */
#define CANXCP_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ CanXcp_Config
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ CanXcp_IsMultiConfig
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ CanXcp_NoMultiConfig
 ----------------------------------------------------------------------------- */

CONST(CanXcp_ConfigType, CANXCP_PBCFG) CanXcp_Config_EcuMConfiguration = 
{
  CanXcp_PduIdField
};




/* PRQA S 5087 5 */ /* MISRA rule 19.1 violation due to AUTOSAR requirement for Memory Mapping */


#define CANXCP_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


/* PRQA S 5087 5 */ /* MISRA rule 19.1 violation due to AUTOSAR requirement for Memory Mapping */
#define CANXCP_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ CanXcp_PduField
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ CanXcp_NoMultiConfig
 ----------------------------------------------------------------------------- */

CONST(CanXcp_XcpPduType, CANXCP_PBCFG) CanXcp_PduIdField[1] = 
{
  
  {
    0 /* XcpMaster__CAN00 */, 
    3 /* XcpSlave__CAN00 */
  }
};




#define CANXCP_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"






