/* -----------------------------------------------------------------------------
  Filename:    Com_Lcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\synergy_projects_working\Haitec\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-01-22  15:41:14
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
#define V_IL_ASRCOM_LCFG_SOURCE
#include "Com.h"
#include "Appl_Cbk.h"
#include "Rte_Cbk.h"
#include "Com_Cbk.h"
#if (COM_ISSM == STD_ON)
#include "Issm_Cbk.h"
#endif

#if (COM_DEV_ERROR_DETECT == STD_ON)
#include "Det.h"
#endif

/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */

/* -----------------------------------------------------------------------------
    &&&~ Version Checks
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
#if !defined(V_SUPPRESS_EXTENDED_VERSION_CHECK)
#if (IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION != 0x05)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION != 0x15)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION != 0x04)
#error "Com_Lcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION in generated File!"
#endif

#endif

/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Consistency Checks
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComLinktimeCRC */
/* Consistency Check No. 1 */
#if (COM_MAXTXIPDUCNT > COM_SINT16_MAX)
#  error "Com_Lcfg.c : COM_MAXTXIPDUCNT is greater than L_ASRCOM_SINT16_MAX"
#endif


/* Consistency Check No.2 */
#if (COM_MAXRXIPDUCNT > COM_SINT16_MAX)
#  error "Com_Lcfg.c : COM_MAXRXIPDUCNT is greater than L_ASRCOM_SINT16_MAX"
#endif


/* Consistency Check No.3 */
#if (COM_RXUBCNT > COM_SINT16_MAX)
# error "Com_Lcfg.c : COM_RXUBCNT is greater than COM_SINT16_MAX!"
#endif


/* END of Checksum exclude for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Il_AsrCom RAM Arrays
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_Buffer[40];

#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Layer Management
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_LMgt_IPduGroupState[COM_SUBIPDUGROUPCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_LMgt_RxPduGroupState[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_LMgt_TxPduGroupState[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Update Bit Handler
 ----------------------------------------------------------------------------- */

/* Update Bit Support is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Deadline Monitor
 ----------------------------------------------------------------------------- */

/* Com_RxDlMon_TimeoutTime: No Rx Ipdus configured */


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Notification Handler
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_RxNHdlr_HandleIPduDeferred[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Rx Lower Layer Interface
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(PduInfoType, COM_VAR_NOINIT) com_RxLLIf_TpPduInfo[COM_MAXRXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Mode Handler
 ----------------------------------------------------------------------------- */

#if (COM_TXMODEHDLR_CYCLIC_TRANSMISSION == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_CycleTimeCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxModeHdlr_CyclicSendRequest[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

#if (COM_TXMODEHDLR_MINIMUM_DELAY == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

volatile VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_DelayTimeCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxModeHdlr_TransmitRequest[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(Com_TxModeHdlr_TxModeHdlType, COM_VAR_NOINIT) com_TxModeHdlr_CurrentTxMode[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#if (COM_TXMODEHDLR_DIRECT_REPETITION == STD_ON)
#define COM_START_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint16, COM_VAR_NOINIT) com_TxModeHdlr_RepCycleCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_16BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(uint8, COM_VAR_NOINIT) com_TxModeHdlr_RepetitionCnt[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif



/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Lower Layer Interface
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(Com_TxLLIf_TpPduInfoType, COM_VAR_NOINIT) com_TxLLIf_TpPduInfo[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Notification Handler
 ----------------------------------------------------------------------------- */

#if ((COM_TXCONFIRMATION_IMMEDIATE == STD_ON) || (COM_TXCONFIRMATION_DEFERRED == STD_ON))
#define COM_START_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

VAR(boolean, COM_VAR_NOINIT) com_TxNHdlr_HandleIPduDeferred[COM_MAXTXIPDUCNT];
#define COM_STOP_SEC_VAR_NOINIT_BOOLEAN
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif



/* Tx error notifications disabled */



/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Signal Interface
 ----------------------------------------------------------------------------- */

/* Signal Groups are not used */


/* -----------------------------------------------------------------------------
    &&&~ Global Arrays: Tx Deadline Monitor
 ----------------------------------------------------------------------------- */

/* Com_RxDlMon_TimeoutTime: No Tx Ipdus configured */


/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Layer Management Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#if (COM_CRC_CHECK == STD_ON)
#define COM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(uint32, COM_CONST) Com_LMgt_LinktimeCRC = (uint32) 0xD46AF5FC;
#define COM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Rx Indication Handling
 ----------------------------------------------------------------------------- */

#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_NotificationIdxType, COM_CONST) Com_RxNHdlr_NotificationCnt = COM_RXSIGALLNOTIFICATIONCNT;
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_RxNHdlr_NotiFuncPtrType, COM_CONST) Com_RxNHdlr_NotificationFuncPtr[COM_RXSIGALLNOTIFICATIONCNT] = 
{
  NULL_PTR /* no notification call back function */, 
  Appl_COMCbk_Com_BCM_Key_Sta__BCM1__CAN00 /* Signal Handle: 0, Com_BCM_Key_Sta__BCM1__CAN00 */, 
  Appl_COMCbk_Com_CAN_N__ECM1__CAN00 /* Signal Handle: 1, Com_CAN_N__ECM1__CAN00 */, 
  Appl_COMCbk_Com_VehSpeed__ABS2__CAN00 /* Signal Handle: 3, Com_VehSpeed__ABS2__CAN00 */
};

#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"





/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* No Rx I-PDU callouts configured */
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Rx Signal Invalidation Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* Rx signal invalidation is deactivated */
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* -----------------------------------------------------------------------------
    &&&~ Tx Confirmation Handling
 ----------------------------------------------------------------------------- */

#if ((COM_TXCONFIRMATION_IMMEDIATE == STD_ON) || (COM_TXCONFIRMATION_DEFERRED == STD_ON))
#if (COM_DEV_ERROR_DETECT == STD_ON)
#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_TxNHdlr_NotificationIdxType, COM_CONST) Com_TxNHdlr_NotificationCnt = COM_TXSIGNOTIFICATIONCNT;
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif

#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_TxNHdlr_NotiFuncPtrType, COM_CONST) Com_TxNHdlr_NotificationFuncPtr[COM_TXSIGNOTIFICATIONCNT] = 
{
  Appl_COMCbkTAck_Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 /* Signal Handle: 7, Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 */
};
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"



#endif




/* -----------------------------------------------------------------------------
    &&&~ Tx Error Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx error notifications disabled */


/* -----------------------------------------------------------------------------
    &&&~ Tx Timeout Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx timeout notifications disabled */



/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Signal Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
/* Tx signal invalidation is deactivated */
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Tx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#if (COM_TXPDUCALLOUT == STD_ON)
#define COM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_TxLLIf_PduCalloutFuncPtrType, COM_CONST) Com_TxLLIf_PduCallout[COM_MAXTXCALLOUTCNT] = 
{
  NULL_PTR, 
  Appl_COMCout_Pdu_EPAS1__CAN00
};
#define COM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#endif


/* END of Checksum include for
  - Il_AsrComLinktimeCRC */



