/* -----------------------------------------------------------------------------
  Filename:    Com_PBcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\synergy_projects_working\Haitec\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-01-22  15:41:14
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define V_IL_ASRCOM_PBCFG_SOURCE
#include "Com.h"
/* -----------------------------------------------------------------------------
    &&&~ Version Checks
 ----------------------------------------------------------------------------- */

#if !defined(V_SUPPRESS_EXTENDED_VERSION_CHECK)
#if (IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION != 0x05)
#error "Com_PBcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION != 0x15)
#error "Com_PBcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION in generated File!"
#endif

#if (IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION != 0x04)
#error "Com_PBcfg.c : Incompatible IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION in generated File!"
#endif

#endif



#define COM_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

CONST(Com_ConfigType, COM_PBCFG) Com_ConfigStruct = 
{
  Com_16BitValue /* uint16  Com_16BitValue[COM_16BITVALUECNT] */, 
  (uint32) 0x00 /* uint32 Com_LMgt_ConfigurationId */, 
  Com_LMgt_ConfigurationString /* Com_CharType Com_LMgt_ConfigurationString[] */, 
  (Com_PduGroupIdType) 2 /* Com_PduGroupIdType Com_LMgt_SubIPduGroupCnt */, 
  Com_LMgt_IPduGroup2IPdus /* Com_LMgt_IPduGroup2IPdusType Com_LMgt_IPduGroup2IPdus[COM_IPDUGROUPCNT + 1] */, 
  Com_LMgt_IPduGroup2IPdusIndirection /* PduIdType Com_LMgt_IPduGroup2IPdusIndirectionCOM_LMGT_IPDUGROUP2IPDUSTARGETCOUNT] */, 
  (Com_PduGroupIdType) 2 /* Com_PduGroupIdType Com_LMgt_IPduGroupCnt */, 
  (Com_SignalIdType) 16 /* Com_SignalIdType Com_Signal_SignalCnt */, 
  (Com_SignalIdType) 4 /* Com_SignalIdType Com_Signal_RxSignalCnt */, 
  Com_Signal_SignalAttributes /* Com_Signal_SignalAttrType Com_Signal_SignalAttributes[COM_SIGNALCNT + 1] */, 
  (PduIdType) 3 /* PduIdType Com_RxBuffer_RxIpduCnt */, 
  Com_RxBuffer_IpduInitValue /* uint8 Com_RxBuffer_IpduInitValue[] */, 
  Com_RxBuffer_IpduInfo /* Com_RxBuffer_IpduInfoType Com_RxBuffer_IpduInfo[COM_RXIPDUCNT] */, 
  Com_RxNHdlr_Ipdu2NotificationFunctions /* Com_RxNHdlr_NotificationIdxType Com_RxNHdlr_Ipdu2NotificationFunctions[COM_MAXRXIPDUCNT + 1] */, 
  Com_RxNHdlr_NotiFuncIndirection /* Com_RxNHdlr_NotiFuncIndirectionType Com_RxNHdlr_NotiFuncIndirection[COM_RXSIGNOTIFICATIONCNT] */, 
  (PduIdType) 2 /* PduIdType Com_TxBuffer_TxIpduCnt */, 
  Com_TxBuffer_IpduInitValue /* uint8 Com_TxBuffer_IpduInitValue[] */, 
  Com_TxBuffer_IpduInfo /* Com_TxBuffer_IpduInfoType Com_TxBuffer_IpduInfo[COM_TXIPDUCNT] */, 
  Com_TxNHdlr_Ipdu2NotificationFunctions /* Com_TxNHdlr_NotificationIdxType Com_TxNHdlr_Ipdu2NotificationFunctions[COM_MAXTXIPDUCNT + 1] */, 
  Com_TxNHdlr_NotiFuncIndirection /* Com_TxNHdlr_NotificationIdxType Com_TxNHdlr_NotiFuncIndirection[COM_TXSIGNOTIFICATIONCNT] */, 
  Com_TxSigIf_Signal2UbBitPos /* Com_Signal_SignalBitPositionType Com_TxSigIf_Signal2UbBitPos[COM_TXSIGNALCNT] */, 
  Com_TxModeHdlr_TxModeTrue /* Com_TxModeHdlr_TxModeHdlType Com_TxModeHdlr_TxModeTrue[COM_TXIPDUCNT] */, 
  Com_TxModeHdlr_TxMode /* Com_TxModeHdlr_TxModeType Com_TxModeHdlr_TxMode[COM_MAXTXMODECNT] */, 
  Com_TxLLIf_ClearUbMask /* uint8 Com_TxLLIf_ClearUbMask[] */, 
  Com_TxLLIf_PduCalloutIndirection /* Com_TxLLIf_PduCalloutIdType Com_TxLLIf_PduCalloutIndirection[COM_TXIPDUCNT] */, 
  Com_TxLLIf_IsTpLayerIpdu /* uint8* Com_TxLLIf_IsTpLayerIpdu[COM_TXIPDUCNT] */, 
  (uint16) 0xC0DE /* the last uint16 in the Com_ConfigStruct must be 0xC0DE */
};

#define COM_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"


#define COM_START_SEC_PBCFG
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Global Configuration Data
 ----------------------------------------------------------------------------- */

CONST(uint16, COM_PBCFG) Com_16BitValue[COM_16BITVALUECNT] = 
{
  0x0001 /* Handle:   0, uint16:      1, sint16:       1 */, 
  0x0001 /* Handle:   1, uint16:      1, sint16:       1 */
};

/* #if ((COM_TXMODEHDLR_TMS == STD_ON) || (COM_TXINV == STD_ON) || (COM_RXINV == STD_ON))
CONST(uint8, COM_PBCFG) Com_8BitValue[COM_8BITVALUECNT]
CONST(uint32, COM_PBCFG) Com_32BitValue[COM_32BITVALUECNT]
#endif */
CONST(Com_CharType, COM_PBCFG) Com_LMgt_ConfigurationString[] = 
{
  (Com_CharType) 0x00
};


/* -----------------------------------------------------------------------------
    &&&~ Layer Management Configuration Data
 ----------------------------------------------------------------------------- */

/* No I-Pdu Group Hierarchy existent. */

CONST(Com_LMgt_IPduGroup2IPdusType, COM_PBCFG) Com_LMgt_IPduGroup2IPdus[COM_IPDUGROUPCNT + 1] = 
{
  (Com_LMgt_IPduGroup2IPdusType) 0 /* Handle: 0 - ComIPduGroup: PduGrp_EPAS__CAN00_Rx */, 
  (Com_LMgt_IPduGroup2IPdusType) 3 /* Handle: 1 - ComIPduGroup: PduGrp_EPAS__CAN00_Tx */, 
  (Com_LMgt_IPduGroup2IPdusType) 5 /* Stop element */
};
CONST(PduIdType, COM_PBCFG) Com_LMgt_IPduGroup2IPdusIndirection[COM_LMGT_IPDUGROUP2IPDUSTARGETCOUNT] = 
{
  (PduIdType) 0 /* Handle: 0 - ComIPduGroup: PduGrp_EPAS__CAN00_Rx - ComRxPdu: Pdu_ABS2__CAN00 */, 
  (PduIdType) 1 /* Handle: 1 - ComIPduGroup: PduGrp_EPAS__CAN00_Rx - ComRxPdu: Pdu_BCM1__CAN00 */, 
  (PduIdType) 2 /* Handle: 2 - ComIPduGroup: PduGrp_EPAS__CAN00_Rx - ComRxPdu: Pdu_ECM1__CAN00 */, 
  (PduIdType) 4 /* Handle: 3 - ComIPduGroup: PduGrp_EPAS__CAN00_Tx - ComTxPdu: Pdu_EPAS1__CAN00 */, 
  (PduIdType) 3 /* Handle: 4 - ComIPduGroup: PduGrp_EPAS__CAN00_Tx - ComTxPdu: Pdu_EPAS2__CAN00 */
};



/* -----------------------------------------------------------------------------
    &&&~ Signal Layer Configuration Data
 ----------------------------------------------------------------------------- */

/* Com_Signal_SignalAttributes: Size,  BitPosition, I-Pdu, AccessAttributes, FilterHdl */
CONST(Com_Signal_SignalAttrType, COM_PBCFG) Com_Signal_SignalAttributes[COM_SIGNALCNT + 1] = 
{
  { 2, 6, 0x01, (Com_Signal_AccessAttrType) 0x0102 /* tAppl uint8 , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 0, Com_BCM_Key_Sta__BCM1__CAN00 */, 
  { 16, 24, 0x02, (Com_Signal_AccessAttrType) 0x4408 /* tAppl uint16, tAcc nByte         , equal length, no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 1, Com_CAN_N__ECM1__CAN00 */, 
  { 1, 1, 0x02, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 2, Com_LV_CAN_N_ERR__ECM1__CAN00 */, 
  { 12, 12, 0x00, (Com_Signal_AccessAttrType) 0x1008 /* tAppl uint16, tAcc nBitnByte     , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 3, Com_VehSpeed__ABS2__CAN00 */, 
  { 8, 0, 0x00, (Com_Signal_AccessAttrType) 0x4202 /* tAppl uint8 , tAcc byte          , equal length, no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 4, Com_Elect_PWR_Consumpt__EPAS2__CAN00 */, 
  { 1, 15, 0x00, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 5, Com_EpasFailed__EPAS2__CAN00 */, 
  { 1, 14, 0x00, (Com_Signal_AccessAttrType) 0x0102 /* tAppl uint8 , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 6, Com_Rel_Steer_Wheel_Ang_Validity__EPAS2__CAN00 */, 
  { 16, 48, 0x00, (Com_Signal_AccessAttrType) 0x4408 /* tAppl uint16, tAcc nByte         , equal length, no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 7, Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 */, 
  { 16, 8, 0x01, (Com_Signal_AccessAttrType) 0x4408 /* tAppl uint16, tAcc nByte         , equal length, no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 8, Com_SAS_Angle__EPAS1__CAN00 */, 
  { 1, 25, 0x01, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 9, Com_SAS_CAL__EPAS1__CAN00 */, 
  { 4, 32, 0x01, (Com_Signal_AccessAttrType) 0x0102 /* tAppl uint8 , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 10, Com_SAS_CheckSum__EPAS1__CAN00 */, 
  { 1, 47, 0x01, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 11, Com_SAS_Init__EPAS1__CAN00 */, 
  { 4, 36, 0x01, (Com_Signal_AccessAttrType) 0x0102 /* tAppl uint8 , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 12, Com_SAS_MsgCount__EPAS1__CAN00 */, 
  { 1, 24, 0x01, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 13, Com_SAS_OK__EPAS1__CAN00 */, 
  { 1, 8, 0x00, (Com_Signal_AccessAttrType) 0x0101 /* tAppl bool  , tAcc nBit          , diff length , no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 14, Com_Steering_Torque_V__EPAS2__CAN00 */, 
  { 8, 16, 0x00, (Com_Signal_AccessAttrType) 0x4202 /* tAppl uint8 , tAcc byte          , equal length, no sign conv. */, (Com_Signal_FilterHdlType) 0xFFFF } /* Signal Handle: 15, Com_Steering_Torque__EPAS2__CAN00 */, 
  { 0, 0, 0x00, (Com_Signal_AccessAttrType) 0xC0DE /* This value should always be 0xC0DE. */, (Com_Signal_FilterHdlType) 0xFFFF }
};

/* No Signal Groups configured */


/* -----------------------------------------------------------------------------
    &&&~ Rx Buffer Configuration Data
 ----------------------------------------------------------------------------- */

CONST(uint8, COM_PBCFG) Com_RxBuffer_IpduInitValue[24] = 
{
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00, 
  0x00
};
CONST(Com_RxBuffer_IpduInfoType, COM_PBCFG) Com_RxBuffer_IpduInfo[3] = 
{
  { (PduLengthType) 0x08, (uint16) 0, (uint16) 0 } /* IPdu Handle: 0, Pdu_ABS2__CAN00 */, 
  { (PduLengthType) 0x08, (uint16) 8, (uint16) 8 } /* IPdu Handle: 1, Pdu_BCM1__CAN00 */, 
  { (PduLengthType) 0x08, (uint16) 16, (uint16) 16 } /* IPdu Handle: 2, Pdu_ECM1__CAN00 */
};


/* -----------------------------------------------------------------------------
    &&&~ Rx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Rx Indication Handling
 ----------------------------------------------------------------------------- */

CONST(Com_RxNHdlr_NotificationIdxType, COM_PBCFG) Com_RxNHdlr_Ipdu2NotificationFunctions[COM_MAXRXIPDUCNT + 1] = 
{
  (Com_RxNHdlr_NotificationIdxType) 0x00 /* IPdu Handle: 0, Pdu_ABS2__CAN00 */, 
  (Com_RxNHdlr_NotificationIdxType) 0x01 /* IPdu Handle: 1, Pdu_BCM1__CAN00 */, 
  (Com_RxNHdlr_NotificationIdxType) 0x02 /* IPdu Handle: 2, Pdu_ECM1__CAN00 */, 
  (Com_RxNHdlr_NotificationIdxType) 0x03 /* Stop Element */
};

CONST(Com_RxNHdlr_NotiFuncIndirectionType, COM_PBCFG) Com_RxNHdlr_NotiFuncIndirection[COM_RXSIGNOTIFICATIONCNT] = 
{
  { (Com_RxNHdlr_NotificationIdxType) 3 } /* Com_VehSpeed__ABS2__CAN00 */, 
  { (Com_RxNHdlr_NotificationIdxType) 1 } /* Com_BCM_Key_Sta__BCM1__CAN00 */, 
  { (Com_RxNHdlr_NotificationIdxType) 2 } /* Com_CAN_N__ECM1__CAN00 */
};

/* Rx indication flags disabled */


/* -----------------------------------------------------------------------------
    &&&~ Rx Timeout Notification Handling
 ----------------------------------------------------------------------------- */

/* Rx timeout notifications disabled */
/* Rx indication flags disabled */




/* -----------------------------------------------------------------------------
    &&&~ Rx Update Bit Configuration Data
 ----------------------------------------------------------------------------- */

/* Update Bit Support is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Rx Deadline Monitor Configuration Data
 ----------------------------------------------------------------------------- */

/* Com_RxDlMon_TimeoutTime: No Rx Ipdus configured */
/* Com_RxDlMon_TimeoutTime: No Rx Ipdus configured */
/* Com_RxDlMon_IpduTimeoutMask: No Rx Ipdus configured */


/* -----------------------------------------------------------------------------
    &&&~ Rx Signal Invalidation Configuration Data
 ----------------------------------------------------------------------------- */

/* Rx signal invalidation is deactivated */


/* -----------------------------------------------------------------------------
    &&&~ Tx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

/* No Rx I-PDU callouts configured */


/* -----------------------------------------------------------------------------
    &&&~ Tx Buffer Configuration Data
 ----------------------------------------------------------------------------- */

CONST(uint8, COM_PBCFG) Com_TxBuffer_IpduInitValue[16] = 
{
  0x00, 0x00, 0x80, 0x00, 0x00, 0x4E, 0x20, 0x00, 0x23, 0x29, 0x00, 0x01, 
  0x00, 0x00, 0x00, 0x00
};

CONST(Com_TxBuffer_IpduInfoType, COM_PBCFG) Com_TxBuffer_IpduInfo[2] = 
{
  { (PduLengthType) 0x08, (uint16) 24, (uint16) 0 } /* IPdu Handle: 0, Pdu_EPAS2__CAN00 */, 
  { (PduLengthType) 0x08, (uint16) 32, (uint16) 8 } /* IPdu Handle: 1, Pdu_EPAS1__CAN00 */
};



/* -----------------------------------------------------------------------------
    &&&~ Tx Notification Handler Configuration Data
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Tx Confirmation Handling
 ----------------------------------------------------------------------------- */

#if ((COM_TXCONFIRMATION_IMMEDIATE == STD_ON) || (COM_TXCONFIRMATION_DEFERRED == STD_ON))
CONST(Com_TxNHdlr_NotificationIdxType, COM_PBCFG) Com_TxNHdlr_Ipdu2NotificationFunctions[COM_MAXTXIPDUCNT + 1] = 
{
  (Com_TxNHdlr_NotificationIdxType) 0x00, 
  (Com_TxNHdlr_NotificationIdxType) 0x01, 
  (Com_TxNHdlr_NotificationIdxType) 0x01
};

CONST(Com_TxNHdlr_NotificationIdxType, COM_PBCFG) Com_TxNHdlr_NotiFuncIndirection[COM_TXSIGNOTIFICATIONCNT] = 
{
  (Com_TxNHdlr_NotificationIdxType) 0 /* Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 */
};


#endif




/* -----------------------------------------------------------------------------
    &&&~ Tx Timeout Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx timeout notifications disabled */



/* -----------------------------------------------------------------------------
    &&&~ Tx Error Notification Handling
 ----------------------------------------------------------------------------- */

/* Tx error notifications disabled */




/* -----------------------------------------------------------------------------
    &&&~ Tx Signal Interface Configuration Data
 ----------------------------------------------------------------------------- */

#if (COM_TXUBHDLR == STD_ON)
CONST(Com_Signal_SignalBitPositionType, COM_PBCFG) Com_TxSigIf_Signal2UbBitPos[COM_TXSIGNALCNT] = 
{
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 0, Com_Elect_PWR_Consumpt__EPAS2__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 1, Com_EpasFailed__EPAS2__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 2, Com_Rel_Steer_Wheel_Ang_Validity__EPAS2__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 3, Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 4, Com_SAS_Angle__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 5, Com_SAS_CAL__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 6, Com_SAS_CheckSum__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 7, Com_SAS_Init__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 8, Com_SAS_MsgCount__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 9, Com_SAS_OK__EPAS1__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 10, Com_Steering_Torque_V__EPAS2__CAN00 */, 
  (Com_Signal_SignalBitPositionType) 0xFFFF /* Signal Handle: 11, Com_Steering_Torque__EPAS2__CAN00 */
};

/* Signal Group Interface is not used */
#endif



/* -----------------------------------------------------------------------------
    &&&~ Tx Mode Handler Configuration Data
 ----------------------------------------------------------------------------- */

CONST(Com_TxModeHdlr_TxModeHdlType, COM_PBCFG) Com_TxModeHdlr_TxModeTrue[COM_TXIPDUCNT] = 
{
  (Com_TxModeHdlr_TxModeHdlType) 0 /* IPdu Handle: 0, Pdu_EPAS2__CAN00 */, 
  (Com_TxModeHdlr_TxModeHdlType) 0 /* IPdu Handle: 1, Pdu_EPAS1__CAN00 */
};

CONST(Com_TxModeHdlr_TxModeType, COM_PBCFG) Com_TxModeHdlr_TxMode[COM_MAXTXMODECNT] = 
{
  { 0x02 /* Periodic */, 0 /* ParamRef */ } /* TxModeTrue: Handle: 0, Offset: 0, Period: 10 */, 
  { 0x02 /* Periodic */, 0 /* ParamRef */ } /* TxModeFalse: Handle: 1, Offset: 0, Period: 10 */
};

#if (COM_TXMODEHDLR_MINIMUM_DELAY == STD_ON)
CONST(uint16, COM_PBCFG) Com_TxModeHdlr_MinDelayTime[COM_MAXTXIPDUCNT] = 
{
  (uint16) 0 /* IPdu Handle: 0, Pdu_EPAS2__CAN00 */, 
  (uint16) 0 /* IPdu Handle: 1, Pdu_EPAS1__CAN00 */
};

#endif




/* -----------------------------------------------------------------------------
    &&&~ Tx Lower Layer Interface Configuration Data
 ----------------------------------------------------------------------------- */

#if (COM_TXUBHDLR == STD_ON)
CONST(uint8, COM_PBCFG) Com_TxLLIf_ClearUbMask[16] = 
{
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 
  0xFF, 0xFF, 0xFF, 0xFF
};

#endif


#if (COM_TXPDUCALLOUT == STD_ON)
CONST(Com_TxLLIf_PduCalloutIdType, COM_PBCFG) Com_TxLLIf_PduCalloutIndirection[COM_TXIPDUCNT] = 
{
  (Com_TxLLIf_PduCalloutIdType) 0 /* IPdu Handle: 0, Pdu_EPAS2__CAN00 */, 
  (Com_TxLLIf_PduCalloutIdType) 1 /* IPdu Handle: 1, Pdu_EPAS1__CAN00 */
};

#endif

CONST(uint8, COM_PBCFG) Com_TxLLIf_IsTpLayerIpdu[COM_TXIPDUCNT] = 
{
  (uint8) 0 /* IPdu Handle: 0, Pdu_EPAS2__CAN00 */, 
  (uint8) 0 /* IPdu Handle: 1, Pdu_EPAS1__CAN00 */
};



/* -----------------------------------------------------------------------------
    &&&~ Tx Deadline Monitor Configuration Data
 ----------------------------------------------------------------------------- */

/* Com_TxDlMon_TimeoutTime: No Tx Ipdus configured */


/* -----------------------------------------------------------------------------
    &&&~ Com_PBcfg_PostBuildInfoBlock
 ----------------------------------------------------------------------------- */

#define PostBuildInfo_StartAddress           0x00
#define PostBuildInfo_CpuByteOrder           11
#define PostBuildInfo_WidthOfPointer         0x04
#define PostBuildInfo_StructAlignment        0
#define PostBuildInfo_AlignmentFillPattern   0x00



#define COM_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /*RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"



