/* -----------------------------------------------------------------------------
  Filename:    Com_Cfg.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\synergy_projects_working\Haitec\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2016-01-22  15:41:14
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(COM_CFG_H)
#define COM_CFG_H

/* -----------------------------------------------------------------------------
    &&&~ Generator Version Check
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define IL_ASRCOM_GENTOOL_GENY_MAJOR_VERSION 0x05
#define IL_ASRCOM_GENTOOL_GENY_MINOR_VERSION 0x15
#define IL_ASRCOM_GENTOOL_GENY_PATCH_VERSION 0x04
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Com Version Information
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define IL_ASRCOMDLL_VERSION                 0x0515
#define IL_ASRCOMDLL_RELEASE_VERSION         0x04
/* This number serves to check the compatibility between generated code and static source code */
#define COM_IMPLEMENTATION_VERSION           0x0125
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


#ifndef COM_OSTYPE_AUTOSAR
#define COM_OSTYPE_AUTOSAR
#endif


#ifndef COM_USE_DUMMY_FUNCTIONS
#define COM_USE_DUMMY_FUNCTIONS              STD_OFF
#endif


#ifndef COM_USE_DUMMY_STATEMENT
#define COM_USE_DUMMY_STATEMENT              STD_ON
#endif


#ifndef COM_CPU_TMS470
#define COM_CPU_TMS470
#endif


#ifndef COM_PROCESSOR_TI_TMS470_LS30316U
#define COM_PROCESSOR_TI_TMS470_LS30316U
#endif


#ifndef COM_COMP_TI
#define COM_COMP_TI
#endif


#ifndef COM_CRC_CHECK
#define COM_CRC_CHECK                        STD_OFF
#endif


#ifndef COM_ATOMIC_BIT_ACCESS_IN_BITFIELD
#define COM_ATOMIC_BIT_ACCESS_IN_BITFIELD    STD_OFF
#endif


#ifndef COM_ATOMIC_VARIABLE_ACCESS
#define COM_ATOMIC_VARIABLE_ACCESS           32
#endif


/* -----------------------------------------------------------------------------
    &&&~ Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ General
 ----------------------------------------------------------------------------- */

#define COM_LMGT_RX                          STD_ON
#define COM_LMGT_TX                          STD_ON
#define COM_RXBUFFER                         STD_ON
#define COM_RXLLIF                           STD_ON
#define COM_RXNHDLR                          STD_ON
#define COM_TXUBHDLR                         STD_ON
#define COM_TXBUFFER                         STD_ON
#define COM_TXLLIF                           STD_ON
#define COM_TXNHDLR                          STD_ON
#define COM_DEV_ERROR_DETECT                 STD_ON
#define COM_OPTIMIZE_IDTYPES                 STD_ON
#define COM_TRIGGER_TRANSMISSION_BY_COM      STD_ON
#define COM_PROD_ERROR_DETECT                STD_ON
#define COM_TSI_TESTCODE                     STD_OFF
#define COM_TSC_TESTCODE                     STD_OFF
#define COM_SIGNALIF                         STD_ON
#define COM_SIGNALGROUPIF                    STD_OFF
#define COM_SIGNALCONVERSION                 STD_OFF
#define COM_RX                               STD_ON
#define COM_TX                               STD_ON
#define COM_TXNHDLR_EMULATION                STD_OFF
#define COM_EXTSIGHDLSPACE                   STD_OFF
#define COM_RXPDUCALLOUT                     STD_OFF
#define COM_TXPDUCALLOUT                     STD_ON
#define COM_TPINTERFACE                      STD_ON
#define COM_LARGESIGNAL                      STD_ON
#define COM_LARGECOMIPDU                     STD_ON
#define COM_TMS_SUPPORT                      STD_ON
#define COM_RXSIGNAL_WRACCESS                STD_ON
#define COM_APPLTYPE_BOOLEAN                 STD_ON
#define COM_APPLTYPE_UINT8                   STD_ON
#define COM_APPLTYPE_SINT8                   STD_OFF
#define COM_APPLTYPE_UINT16                  STD_ON
#define COM_APPLTYPE_SINT16                  STD_OFF
#define COM_APPLTYPE_UINT32                  STD_OFF
#define COM_APPLTYPE_SINT32                  STD_OFF
#define COM_APPLTYPE_UINT8N                  STD_OFF
#define COM_BUSACC_NBIT                      STD_ON
#define COM_BUSACC_BYTE                      STD_ON
#define COM_BUSACC_NBYTE                     STD_ON
#define COM_BUSACC_NBYTE_SW                  STD_OFF
#define COM_BUSACC_NBITNBYTE                 STD_ON
#define COM_BUSACC_NBITNBYTE_SW              STD_OFF
#define COM_SIGNEXTENSION                    STD_OFF
#define COM_F_MASKEDNEWDIFOLD                STD_OFF
#define COM_F_MASKEDNEWEQUALSX               STD_OFF
#define COM_F_MASKEDNEWDIFFERSX              STD_OFF
#define COM_F_NEWISOUTSIDE                   STD_OFF
#define COM_F_NEWISWITHIN                    STD_OFF
#define COM_F_NONE                           STD_ON
#define COM_F_NEVER                          STD_OFF
#define COM_F_ALWAYS                         STD_OFF
#define COM_TXCONFIRMATION_DEFERRED          STD_ON
#define COM_TXCONFIRMATION_IMMEDIATE         STD_OFF
#define COM_TXERRORNOTIFICATION              STD_OFF
#define COM_BAC21_COMPATIBILITY              STD_OFF
#define COM_PROTECT_NOTIFICATIONFLAG         STD_ON
#define COM_PROTECT_TIMEOUTFLAG              STD_ON
#define COM_RESET_TIMEOUTFLAG                STD_OFF
#define COM_USE_PDUINFOTYPE                  STD_OFF
#define COM_DYNAMIC_DLC_SUPPORT              STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ API
 ----------------------------------------------------------------------------- */

#define COM_DE_INIT_API                      STD_ON
#define COM_RECEPTION_DM_API                 STD_ON
#define COM_GET_STATUS_API                   STD_ON
#define COM_GET_CONFIGURATION_ID_API         STD_ON
#define COM_GET_CONFIGURATION_STRING_PTR_API STD_ON
#define COM_GET_VERSION_INFO_API             STD_ON
#define COM_TRIGGER_IPDU_SEND_API            STD_ON
#define COM_TRIGGER_TRANSMIT_API             STD_ON
#define COM_MAIN_FUNCTION_RX_API             STD_ON
#define COM_MAIN_FUNCTION_TX_API             STD_ON
#define COM_VSTDLIB_MEM_API                  STD_OFF
#define COM_IPDU_GROUP_TRANSMIT_API          STD_OFF
#define COM_SIGNAL_ACCESS_MACRO_API          STD_OFF
#define COM_TXSIGNAL_ACCESS_MACRO_API        STD_OFF
#define COM_RXSIGNAL_ACCESS_MACRO_API        STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_LMgt
 ----------------------------------------------------------------------------- */

#define COM_LMGT_IPDUGROUPHIERARCHY          STD_OFF
#define COM_LMGT_MULTIPLEIPDUGROUPREF        STD_ON


/* -----------------------------------------------------------------------------
    &&&~ Com_TxModeHdlr
 ----------------------------------------------------------------------------- */

#define COM_TXMODEHDLR                       STD_ON
#define COM_TXMODEHDLR_QUEUE_FAILED_TRANSMISSION_REQUESTS STD_ON
#define COM_TXMODEHDLR_CYCLIC_TRANSMISSION   STD_ON
#define COM_TXMODEHDLR_DIRECT_TRANSMISSION   STD_OFF
#define COM_TXMODEHDLR_DIRECT_REPETITION     STD_OFF
#define COM_TXMODEHDLR_MINIMUM_DELAY         STD_OFF
#define COM_TXMODEHDLR_TMS                   STD_OFF
#define COM_TXMODEHDLR_TXMODEFALSE           STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxDlMon
 ----------------------------------------------------------------------------- */

#define COM_RXDLMON                          STD_OFF
#define COM_RXDLMON_TIMEOUTDEFAULTVALUE      STD_OFF
#define COM_RXDLMON_FIRSTTIMEOUT             STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxUbHdlr
 ----------------------------------------------------------------------------- */

#define COM_RXUBHDLR                         STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXUBHDLR_DEFERRED_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXUBHDLR_NOTIFICATIONFUNCTION    STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_NOTIFICATIONFLAG STD_OFF
#define COM_RXUBHDLR_DEFERRED_NOTIFICATIONFLAG STD_OFF
#define COM_RXUBHDLR_NOTIFICATIONFLAG        STD_OFF
#define COM_RXUBHDLR_TIMEOUTFUNCTION         STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_TIMEOUTFLAG   STD_OFF
#define COM_RXUBHDLR_DEFERRED_TIMEOUTFLAG    STD_OFF
#define COM_RXUBHDLR_TIMEOUTFLAG             STD_OFF
#define COM_RXUBHDLR_IMMEDIATE_SIGNALPROCESSING STD_OFF
#define COM_RXUBHDLR_DEFERRED_SIGNALPROCESSING STD_OFF
#define COM_RXUBHDLR_TIMEOUTDEFAULTVALUE     STD_OFF
#define COM_RXUBHDLR_FIRSTTIMEOUT            STD_OFF
#define COM_RXUBHDLR_TIMEOUT                 STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxInv
 ----------------------------------------------------------------------------- */

#define COM_RXINV                            STD_OFF
#define COM_RXINV_NOTIINVFUNC                STD_OFF
#define COM_RXINV_NOTIINVFUNC_NOUB_TO        STD_OFF
#define COM_RXINV_NOTIINVFUNC_UB_TO          STD_OFF
#define COM_RXINV_NOTIINVFUNC_NOUB           STD_OFF
#define COM_RXINV_NOTIINVFUNC_UB             STD_OFF
#define COM_RXINV_INHIBITNOTIFUNC            STD_OFF
#define COM_RXINV_INHIBITINDFLAG             STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxInv
 ----------------------------------------------------------------------------- */

#define COM_TXINV                            STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_RxNHdlr
 ----------------------------------------------------------------------------- */

#define COM_RXNHDLR_IMMEDIATE_NOTIFICATIONFLAG STD_OFF
#define COM_RXNHDLR_DEFERRED_NOTIFICATIONFLAG STD_OFF
#define COM_RXNHDLR_NOTIFICATIONFLAG         STD_OFF
#define COM_RXNHDLR_IMMEDIATE_TIMEOUTFLAG    STD_OFF
#define COM_RXNHDLR_DEFERRED_TIMEOUTFLAG     STD_OFF
#define COM_RXNHDLR_TIMEOUTFLAG              STD_OFF
#define COM_RXNHDLR_IMMEDIATE_NOTIFICATIONFUNCTION STD_OFF
#define COM_RXNHDLR_DEFERRED_NOTIFICATIONFUNCTION STD_ON
#define COM_RXNHDLR_NOTIFICATIONFUNCTION     STD_ON
#define COM_RXNHDLR_TIMEOUTFUNCTION          STD_OFF
#define COM_RXNHDLR_IMMEDIATE_SIGNALPROCESSING STD_OFF
#define COM_RXNHDLR_DEFERRED_SIGNALPROCESSING STD_ON
#define COM_RXNHDLR_RXFILTER_GRPSIG          STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGGRPINDFLAG   STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGGRPNOTIFUNC  STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGINDFLAG      STD_OFF
#define COM_RXNHDLR_RXFILTER_SIGNOTIFUNC     STD_OFF
#define COM_RXNHDLR_RXFILTER                 STD_OFF
#define COM_RXNHDLR_INHIBITNOTIFUNC          STD_OFF
#define COM_RXNHDLR_INHIBITINDFLAG           STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxSigIf
 ----------------------------------------------------------------------------- */

#define COM_TXSIGIF                          STD_ON
#define COM_TXSIGIF_TRIGGEREDONCHANGE        STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxNHdlr
 ----------------------------------------------------------------------------- */

#define COM_TXNHDLR_TIMEOUTFUNCTION          STD_OFF


/* -----------------------------------------------------------------------------
    &&&~ Com_TxDlMon
 ----------------------------------------------------------------------------- */

#define COM_TXDLMON                          STD_OFF
#define COM_TXDLMON_TXCONFIRMATION           STD_OFF


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Precompile related Precompile Constants
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define COM_CONFIG_VARIANT                   1
#define COM_PRECOMPILE_CRC                   (uint32) 0x95F602F3
#define COM_MAXIPDULENGTH                    8
#define COM_MAXINVVALUELENGTH                8
/* END of Checksum include for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime related Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_ISSM                             STD_OFF
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Linktime related Precompile Constants
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComLinktimeCRC */
#define COM_MAXRXIPDUCNT                     3
#define COM_MAXRXUBCNT                       0
#define COM_MAXTXIPDUCNT                     2
#define COM_RXSIGALLNOTIFICATIONCNT          4
#define COM_RXSIGALLTIMEOUTNOTICNT           1
#define COM_TXSIGNOTIFICATIONCNT             1
#define COM_TXSIGTIMEOUTNOTICNT              0
#define COM_TXSIGERRORNOTICNT                0
#define COM_MAXRXCALLOUTCNT                  1
#define COM_MAXTXCALLOUTCNT                  2
#define COM_MAXTXSIGNALGROUPCNT              0
#define COM_RXSIGALLNOTIFLAGCNT              0
#define COM_RXSIGALLTIMEOUTFLAGCNT           0
#define COM_NOTIFLAGBYTECNT                  0
#define COM_TIMEOUTFLAGBYTECNT               0
#define COM_EXTERNALSIGCNT                   16
#define COM_EXTERNALSIGGRPCNT                0
#define COM_RXINVSIGNALCNT                   0
#define COM_RXINVSIGNALGROUPCNT              0
#define COM_RXINVGROUPSIGNALCNT              0
#define COM_RXINVNOTIINVOBJNOUBCNT           0
/* END of Checksum include for
  - Il_AsrComLinktimeCRC */


/* -----------------------------------------------------------------------------
    &&&~ Postbuild related Precompile Constants
 ----------------------------------------------------------------------------- */

#define COM_8BITVALUECNT                     1
#define COM_16BITVALUECNT                    2
#define COM_32BITVALUECNT                    1
#define COM_RXIPDUCNT                        3
#define COM_TXIPDUCNT                        2
#define COM_RXSIGNOTIFICATIONCNT             3
#define COM_RXSIGTIMEOUTNOTICNT              0
#define COM_RXUBCNT                          0
#define COM_SIGCONVERSIONCNT                 0
#define COM_RXSIGNOTIFLAGCNT                 0
#define COM_RXSIGTIMEOUTFLAGCNT              0
#define COM_SIGNALCNT                        16
#define COM_TXSIGNALCNT                      12
#define COM_RXSIGNALCNT                      4
#define COM_FILTERCNT                        1
#define COM_FILTERSTATEBYTECNT               1
#define COM_MAXTXMODECNT                     2
#define COM_RXNHDLR_FILTERSIGCNT             0
#define COM_RXNHDLR_FILTERSIGGRPCNT          0
#define COM_RXNHDLR_FILTERGRPSIGCNT          0
#define COM_SIGNALGROUPCNT                   0
#define COM_RXSIGNALGROUPCNT                 0
#define COM_TXSIGNALGROUPCNT                 0
#define COM_SUBIPDUGROUPCNT                  2
#define COM_IPDUGROUPCNT                     2
#define COM_LMGT_IPDUGROUP2SUBGROUPSTARGETCOUNT 2
#define COM_LMGT_IPDUGROUP2IPDUSTARGETCOUNT  5


/* -----------------------------------------------------------------------------
    &&&~ Common Precompile Constants
 ----------------------------------------------------------------------------- */

#define COM_PDUID_MAXVAL                     0xFFFF


/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Symbolic Rx Signal Handles
 ----------------------------------------------------------------------------- */

#define Com_BCM_Key_Sta__BCM1__CAN00         (Com_SignalIdType) 0
#define Com_CAN_N__ECM1__CAN00               (Com_SignalIdType) 1
#define Com_LV_CAN_N_ERR__ECM1__CAN00        (Com_SignalIdType) 2
#define Com_VehSpeed__ABS2__CAN00            (Com_SignalIdType) 3


/* -----------------------------------------------------------------------------
    &&&~ Symbolic Tx Signal Handles
 ----------------------------------------------------------------------------- */

#define Com_Elect_PWR_Consumpt__EPAS2__CAN00 (Com_SignalIdType) 4
#define Com_EpasFailed__EPAS2__CAN00         (Com_SignalIdType) 5
#define Com_Rel_Steer_Wheel_Ang_Validity__EPAS2__CAN00 (Com_SignalIdType) 6
#define Com_Rel_Steer_Wheel_Ang__EPAS2__CAN00 (Com_SignalIdType) 7
#define Com_SAS_Angle__EPAS1__CAN00          (Com_SignalIdType) 8
#define Com_SAS_CAL__EPAS1__CAN00            (Com_SignalIdType) 9
#define Com_SAS_CheckSum__EPAS1__CAN00       (Com_SignalIdType) 10
#define Com_SAS_Init__EPAS1__CAN00           (Com_SignalIdType) 11
#define Com_SAS_MsgCount__EPAS1__CAN00       (Com_SignalIdType) 12
#define Com_SAS_OK__EPAS1__CAN00             (Com_SignalIdType) 13
#define Com_Steering_Torque_V__EPAS2__CAN00  (Com_SignalIdType) 14
#define Com_Steering_Torque__EPAS2__CAN00    (Com_SignalIdType) 15


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Symbolic Signal Group Handles
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ IPDU Group Symbolic Handles
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define PduGrp_EPAS__CAN00_Rx                (Com_PduGroupIdType) 0
#define PduGrp_EPAS__CAN00_Tx                (Com_PduGroupIdType) 1
/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Signal Gateway Configuration
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Precompile Switches
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define COM_SIGNALGW                         STD_OFF
#define COM_SIGNALGW_RXTIMEOUT               STD_OFF
#define COM_SIGNALGW_RXTIMEOUTUB             STD_OFF
#define COM_SIGNALGW_MSV                     STD_OFF
#define COM_SIGNALGW_STOPTXONRXTIMEOUT       STD_OFF
#define COM_SIGNALGW_CANMOST                 STD_OFF
#define COM_SIGNALGW_UB                      STD_OFF
#define COM_SIGNALGW_TRIGGERTXONINV          STD_OFF
#define COM_SIGNALGW_SUSPENDISRPERPDU        STD_OFF
/* -----------------------------------------------------------------------------
    &&&~ Invalidate Tx On Rx Timeout
 ----------------------------------------------------------------------------- */

#define COM_SIGNALGW_INVSIG_IPDU             STD_OFF
#define COM_SIGNALGW_INVSIG_UB               STD_OFF
#define COM_SIGNALGW_INVSIGGRP_UB            STD_OFF
#define COM_SIGNALGW_INVSIGGRP_IPDU          STD_OFF
#define COM_SIGNALGW_INVTXONRXTO_IPDU        STD_OFF
#define COM_SIGNALGW_INVTXONRXTO_UB          STD_OFF
#define COM_SIGNALGW_INVTXONRXTO             STD_OFF


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */




/* END of Checksum include for
  - Il_AsrComPrecompileCRC */

/* -----------------------------------------------------------------------------
    &&&~ Type Definitions
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Com
 ----------------------------------------------------------------------------- */

typedef VAR(uint8, TYPEDEF) Com_ValueIdxType;


/* -----------------------------------------------------------------------------
    &&&~ Com_RxInv
 ----------------------------------------------------------------------------- */

/* RxInv component is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Com_RxNHdlr
 ----------------------------------------------------------------------------- */

/* RxNHdlr component is disabled */


/* -----------------------------------------------------------------------------
    &&&~ Com_LMgt
 ----------------------------------------------------------------------------- */

typedef VAR(uint8, TYPEDEF) Com_LMgt_IPduGroup2IPdusType;


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Read Access Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal access macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Write Access Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal access macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Signal Invalidation Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* signal invalidation macros are disabled */

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Flag Provider Macros
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
/* -----------------------------------------------------------------------------
    &&&~ Indication Flag Access Macros
 ----------------------------------------------------------------------------- */

/* Indication Flag Access Macros are disabled or not used. */


/* -----------------------------------------------------------------------------
    &&&~ Timeout Flag Access Macros
 ----------------------------------------------------------------------------- */

/* Timeout Flag Access Macros are disabled or not used. */


/* -----------------------------------------------------------------------------
    &&&~ StateOn Flag Access Macros
 ----------------------------------------------------------------------------- */

/* StateOn Flag Access Macros are disabled or not used. */


/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */


/* -----------------------------------------------------------------------------
    &&&~ Com EcuC Configuration Container Name
 ----------------------------------------------------------------------------- */

/* START of Checksum exclude for
  - Il_AsrComPrecompileCRC */
#define ComConfig                            Com_ConfigStruct

/* END of Checksum exclude for
  - Il_AsrComPrecompileCRC */




#endif /* COM_CFG_H */
