/* -----------------------------------------------------------------------------
  Filename:    Com_Cfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Com
               
               Configuration   : C:\Temp\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-07-19  08:51:13
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* START of Checksum include for
  - Il_AsrComPrecompileCRC */
#define V_IL_ASRCOM_CFG_SOURCE
#include "Com.h"
#if ((COM_RXINV == STD_ON) && (COM_SIGNAL_ACCESS_MACRO_API == STD_ON))
#include "Appl_Cbk.h"
#include "Rte_Cbk.h"
#endif

/* -----------------------------------------------------------------------------
    &&&~ Rx Signal Invalidation Configuration Data
 ----------------------------------------------------------------------------- */

/* Rx signal invalidation is deactivated */


/* -----------------------------------------------------------------------------
    &&&~ Reception Filtering Configuration Data
 ----------------------------------------------------------------------------- */

/* Reception filtering is deactivated */


/* END of Checksum include for
  - Il_AsrComPrecompileCRC */

