/* -----------------------------------------------------------------------------
  Filename:    ComM_Lcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: ComM
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-06-29  10:50:49
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#define CCL_ASR_COMM_LCFG_MODULE

/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "ComM.h"
#include "CanSM_ComM.h"
#include "CanSM.h"
#include "Det.h"
#include "Dem.h"
#include "Dcm_Cbk.h"



 /* PRQA S 3458 1 */ /* MD_MSR_19.4 */ 
#define COMM_CHECK_RETVALUE(a, b) { if((a) == E_NOT_OK) { (void)ComM_Assert(COMM_E_ERROR_IN_PROV_SERVICE, b); } }


/* -----------------------------------------------------------------------------
    &&&~ VERSION CHECKS
 ----------------------------------------------------------------------------- */

#if !defined( CCL_ASRCOMM_DISABLE_COMPATIBILITY_CHECK )
  #if defined(CANSM_VENDOR_ID)
    #if(CANSM_VENDOR_ID == 30u)
      #if ( CANSM_AR_MAJOR_VERSION != 1u )
        #error "Incompatible CANSM_AR_MAJOR_VERSION with this ComM Implementation!"
      #endif
      #if ( CANSM_AR_MINOR_VERSION != 0u )
        #error "Incompatible CANSM_AR_MINOR_VERSION with this ComM Implementation!"
      #endif
    #endif
  #endif
  #if ( COMM_PROD_ERROR_DETECT == STD_ON )
  #if defined(DEM_VENDOR_ID)
    #if(DEM_VENDOR_ID == 30u)
      #if ( DEM_AR_MAJOR_VERSION != 2u )
        #error "Incompatible DEM_AR_MAJOR_VERSION with this ComM Implementation!"
      #endif
      #if( ( DEM_AR_MINOR_VERSION != 2u ) && ( DEM_AR_MINOR_VERSION != 1u ) )
        #error "Incompatible DEM_AR_MINOR_VERSION with this ComM Implementation!"
      #endif
    #endif
  #endif
  #endif
  #if ( COMM_DEV_ERROR_DETECT == STD_ON )
  #if defined(DET_VENDOR_ID)
    #if(DET_VENDOR_ID == 30u)
      #if ( DET_AR_MAJOR_VERSION != 2u )
        #error "Incompatible DET_AR_MAJOR_VERSION with this ComM Implementation!"
      #endif
      #if ( DET_AR_MAJOR_VERSION != 2u )
        #error "Incompatible DET_AR_MAJOR_VERSION with this ComM Implementation!"
      #endif
    #endif
  #endif
  #endif
#endif  /* COMM_COMPATIBILITY_CHECK */


/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA ROM
 ----------------------------------------------------------------------------- */

#define COMM_START_SEC_CONST_8BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
CONST(ComM_UserHandleType, COMM_CONST) ComM_MaxNumberOfUsers = (ComM_UserHandleType) COMM_MAX_NUMBER_OF_USERS;
/* ComM_ChannelStopIndex stores the stop index inside the user bit field per channel */
CONST(NetworkHandleType, COMM_CONST) ComM_ChannelStopIndex[COMM_ACTIVE_CHANNEL] =
{
    0
};

/* the variable stores the ComM channel count */
CONST(NetworkHandleType, COMM_CONST) ComM_Active_Channel = (NetworkHandleType)0x1;

CONST(uint8, COMM_CONST) ComM_User_ByteCount = COMM_USER_BYTE;
CONST(uint8, COMM_CONST) ComM_Nm_Type[1] = 
{
    NM_VARIANT_NONE
};

CONST(uint8, COMM_CONST) ComM_InhibitionStatusInitValue[1] = 
{
    0x0
};

CONST(boolean, COMM_CONST) ComM_SyncWakeUp = FALSE;

/* user user byte mask index */
CONST(uint8, COMM_CONST) ComM_UserByteMaskIndex[COMM_MAX_NUMBER_OF_USERS + 1] =
{
   0
,  1
};

#define COMM_STOP_SEC_CONST_8BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"

#define COMM_START_SEC_CONST_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"

/* user byte mask for the access to the user communication request fields */
CONST(ComM_UserByteMaskType, COMM_CONST) ComM_UserByteMask[COMM_MAX_BYTE_MASK] =
{
    {0x0, 0x1, 0xfe, 0x0} /*ComMUser_CAN00*/
};

/* the variable stores the bus type per channel */
CONST(ComM_BusType, COMM_CONST) ComM_ChannelBusType[COMM_ACTIVE_CHANNEL] = 
{
    COMM_BUS_TYPE_CAN
};

CONST(ComM_InhibitionStatusType, COMM_CONST) ComM_ECUGroupClassInit = 0x3;
#define COMM_STOP_SEC_CONST_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
#if (COMM_CRC_CHECK == STD_ON)
#define COMM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, COMM_CONST) ComM_PrecompileCRC = (uint32) 0xD0FFB5B3;
#define COMM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#endif

#define COMM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, COMM_CONST) ComM_GeneratorVersion = 0x031804;
#define COMM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



/* -----------------------------------------------------------------------------
    &&&~ INTERNAL DATA RAM
 ----------------------------------------------------------------------------- */




/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA RAM
 ----------------------------------------------------------------------------- */

#define COMM_START_SEC_VAR_NOINIT_8BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_UserReqFullComArray[COMM_USER_BYTE];             /* user bit field for full communication requests */
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_BusSmState[COMM_ACTIVE_CHANNEL];                      
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_LastBusSmState[COMM_ACTIVE_CHANNEL];                      
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_FrShutdown[COMM_ACTIVE_CHANNEL];                       
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_StateChange[COMM_ACTIVE_CHANNEL];
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_LastStateChange[COMM_MAX_NUMBER_OF_USERS];
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_Dcm_FullReq[COMM_ACTIVE_CHANNEL];
VAR(uint8, COMM_VAR_NOINIT_8BIT)                            ComM_Dcm_SilentReq[COMM_ACTIVE_CHANNEL];
#define COMM_STOP_SEC_VAR_NOINIT_8BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"

#define COMM_START_SEC_VAR_NOINIT_16BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
VAR(uint16, COMM_VAR_NOINIT_16BIT)                          ComM_MinFullComModeTime[COMM_ACTIVE_CHANNEL];         /* minimum full communiation mode duration time */
VAR(uint16, COMM_VAR_NOINIT_16BIT)                          ComM_NmLightTimeout[COMM_ACTIVE_CHANNEL];             /* timer after ready sleep mode is left */
#define COMM_STOP_SEC_VAR_NOINIT_16BIT
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"

#define COMM_START_SEC_VAR_NOINIT_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
VAR(ComM_SubModeType, COMM_VAR_NOINIT_UNSPECIFIED)          ComM_ActiveComMode[COMM_ACTIVE_CHANNEL];              /* ComM current communication mode */
VAR(ComM_SubModeType, COMM_VAR_NOINIT_UNSPECIFIED)          ComM_BusComModeReq[COMM_ACTIVE_CHANNEL];              /* ComM current communication mode */
VAR(ComM_SubModeType, COMM_VAR_NOINIT_UNSPECIFIED)          ComM_BusComModeReqTmp[COMM_ACTIVE_CHANNEL];           /* ComM current communication mode */
#define COMM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"

#define COMM_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"
VAR(ComM_InhibitionType, COMM_APPL_VAR_NVRAM)               ComM_Inhibition;
#define COMM_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
 /* PRQA S 5087 1 */ /* MD_MSR_19.1 */ 
#include "MemMap.h"


#define COMM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ GLOBAL FUNCTION PROTOTYPES
 ----------------------------------------------------------------------------- */

/*********************************************************************************************************************
FUNCTION: ComM_MainFunction_0
----------------------------------------------------------------------------------------------------------------------
API     Type                     Name                    Description
----------------------------------------------------------------------------------------------------------------------
  Input: -
  Output: -
  Return: -
----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
----------------------------------------------------------------------------------------------------------------------
     Called by: upper layer
  Precondition: Communication manager has to be initialized.

  Main function of the communication manager.
*********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_MainFunction_0(void)
{
#if ( COMM_DEV_ERROR_DETECT == STD_ON )
  Std_ReturnType retValue;
  ComM_InitStatusType State;

  retValue = E_OK;

  (void)ComM_GetStatus(&State);
  if(State == COMM_UNINIT)
  {
    Det_ReportError( 12, 0, (uint8)COMM_MAINFUNCTION_ID, (uint8)COMM_E_NOT_INITED);
    retValue = E_NOT_OK;
  }

  if(retValue == E_OK)
#endif
  {
    ComM_MainFunction((NetworkHandleType)0u );
  }
}
/**********************************************************************************************************************
FUNCTION: ComM_DcmIndication
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition indication to the DCM
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_DcmIndication(NetworkHandleType Channel, ComM_ModeType ComM_TargetMode)
{

  uint16 FullReqSum;
  uint16 SilentReqSum;
  NetworkHandleType ChannelTmp;

  FullReqSum = 0;
  SilentReqSum = 0;

  switch(ComM_TargetMode)
  {
    case COMM_NO_COMMUNICATION:
      if(ComM_Dcm_FullReq[Channel] > 0)
      {
        ComM_Dcm_FullReq[Channel]--;
      }

      if(ComM_Dcm_SilentReq[Channel] > 0)
      {
        ComM_Dcm_SilentReq[Channel]--;
      }

      for(ChannelTmp = 0; ChannelTmp < COMM_ACTIVE_CHANNEL; ChannelTmp++)
      {
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        if((ComM_IdentityMapping[ChannelTmp] & ComM_ActiveIdentityMask) != 0u)
        {
#endif
          FullReqSum += ComM_Dcm_FullReq[ChannelTmp];
          SilentReqSum += ComM_Dcm_SilentReq[ChannelTmp];
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        }
#endif
      }

      if((FullReqSum == 0) && (SilentReqSum == 0))
      {
        Dcm_ComM_NoComModeEntered();
      }
      break;
    case COMM_SILENT_COMMUNICATION:
      if(ComM_Dcm_FullReq[Channel] > 0)
      {
        ComM_Dcm_FullReq[Channel]--;
      }

      for(ChannelTmp = 0; ChannelTmp < COMM_ACTIVE_CHANNEL; ChannelTmp++)
      {
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        if((ComM_IdentityMapping[ChannelTmp] & ComM_ActiveIdentityMask) != 0u)
        {
#endif
          FullReqSum += ComM_Dcm_FullReq[ChannelTmp];
          SilentReqSum += ComM_Dcm_SilentReq[ChannelTmp];
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        }
#endif
      }

      if((FullReqSum == 0) && (SilentReqSum == 0))
      {
        Dcm_ComM_SilentComModeEntered();
      }

      ComM_Dcm_SilentReq[Channel]++;
      break;
    case COMM_FULL_COMMUNICATION:
      if(ComM_Dcm_SilentReq[Channel] > 0)
      {
        ComM_Dcm_SilentReq[Channel]--;
      }

      for(ChannelTmp = 0; ChannelTmp < COMM_ACTIVE_CHANNEL; ChannelTmp++)
      {
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        if((ComM_IdentityMapping[ChannelTmp] & ComM_ActiveIdentityMask) != 0u)
        {
#endif
          FullReqSum += ComM_Dcm_FullReq[ChannelTmp];
#if (COMM_IDENTITY_MANAGER_CONFIG == STD_ON)
        }
#endif
      }

      if(FullReqSum == 0)
      {
        Dcm_ComM_FullComModeEntered();
      }

      ComM_Dcm_FullReq[Channel]++;
      break;
    default:
      /* nothing to do */
      break;
  }
}
/**********************************************************************************************************************
FUNCTION: ComM_NOCOM_NETREQ
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from No Communication to Network Requested
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_NOCOM_NETREQ(NetworkHandleType Channel)
{
  Std_ReturnType retValue_ServiceFct;

  retValue_ServiceFct = CanSM_RequestComMode(  Channel, COMM_FULL_COMMUNICATION);
  COMM_CHECK_RETVALUE(retValue_ServiceFct, 0x60)
  ComM_MinFullComModeTime[Channel] = 1;

}
/**********************************************************************************************************************
FUNCTION: ComM_NOCOM_READYS
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from No Communication to Ready Sleep
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_NOCOM_READYS(NetworkHandleType Channel)
{
  Std_ReturnType retValue_ServiceFct;

  retValue_ServiceFct = CanSM_RequestComMode(  Channel, COMM_FULL_COMMUNICATION);
  COMM_CHECK_RETVALUE(retValue_ServiceFct, 0x60)


}
/**********************************************************************************************************************
FUNCTION: ComM_SICOM
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from full to silent communication
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_SICOM(NetworkHandleType Channel)
{

  Channel = Channel;
}
/**********************************************************************************************************************
FUNCTION: ComM_READYS_NETREQ
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Ready Sleep to Network Requested
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_READYS_NETREQ(NetworkHandleType Channel)
{

  Channel = Channel;

}
/**********************************************************************************************************************
FUNCTION: ComM_SICOM_NOCOM
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Silent Communication to No Communication
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_SICOM_NOCOM(NetworkHandleType Channel)
{
  Std_ReturnType retValue_ServiceFct;

  retValue_ServiceFct = CanSM_RequestComMode(Channel, COMM_NO_COMMUNICATION);
  COMM_CHECK_RETVALUE(retValue_ServiceFct, 0x60)


}
/**********************************************************************************************************************
FUNCTION: ComM_SICOM_NETREQ
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Silent Communication to Network Requested
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_SICOM_NETREQ(NetworkHandleType Channel)
{

  Channel = Channel;

}
/**********************************************************************************************************************
FUNCTION: ComM_SICOM_READYS
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Silent Communication to Network Requested
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_SICOM_READYS(NetworkHandleType Channel)
{

  Channel = Channel;

}
/**********************************************************************************************************************
FUNCTION: ComM_NETREQ_READYS
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Network Requested to Ready Sleep
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_NETREQ_READYS(NetworkHandleType Channel)
{

  Channel = Channel;
}
/**********************************************************************************************************************
FUNCTION: ComM_NO_TRANS
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for an no state transition
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_NO_TRANS(NetworkHandleType Channel)
{


  Channel = Channel;

  ComM_Assert(COMM_E_NOSUPPORTED_MODECHANGE, 0x60);

}
/**********************************************************************************************************************
FUNCTION: ComM_EnterModeNoCommunication
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM state transition from Network Requested to Ready Sleep
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_EnterModeNoCommunication(NetworkHandleType Channel)
{


  Channel = Channel;

}

/**********************************************************************************************************************
FUNCTION: ComM_GetCurrentBusSMMode)
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function of the ComM get the current communication mode
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_GetCurrentBusSMMode(NetworkHandleType Channel, P2VAR(ComM_ModeType, AUTOMATIC, COMM_APPL_VAR) ComMode)
{

  Std_ReturnType retValue_ServiceFct;

  retValue_ServiceFct = CanSM_GetCurrentComMode(Channel, ComMode);
  COMM_CHECK_RETVALUE(retValue_ServiceFct, 0x08)
}
/**********************************************************************************************************************
FUNCTION: ComM_LoadNonVolatileValues
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM to read the ComM specific non-volatile data
**********************************************************************************************************************/
FUNC(Std_ReturnType, COMM_CODE) ComM_LoadNonVolatileValues(void)
{

  return E_NOT_OK;
}
/**********************************************************************************************************************
FUNCTION: ComM_StoreNonVolatileValues
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Container function for the ComM to store the ComM specific non-volatile data
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_StoreNonVolatileValues(void)
{

}
/**********************************************************************************************************************
FUNCTION: ComM_DemReportError
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  The function reports the ComM DEM errors.
**********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_DemReportError(NetworkHandleType  Channel)
{

  Channel = Channel;

}
/**********************************************************************************************************************
FUNCTION: ComM_ServiceLimitChannelToNoComMode)
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  limit the given network channel to the given mode 
**********************************************************************************************************************/
FUNC(Std_ReturnType, COMM_CODE) ComM_ServiceLimitChannelToNoComMode(ComM_NetworkHandleType Channel, boolean Status)
{

   return ComM_LimitChannelToNoComMode((NetworkHandleType)Channel, Status);
}
/**********************************************************************************************************************
FUNCTION: ComM_ServicePreventWakeUp)
-----------------------------------------------------------------------------------------------------------------------
 API     Type                    Name                    Description
-----------------------------------------------------------------------------------------------------------------------
   Input: -                       -                       -
  Output: -                       -                       -
  Return: -                       -                       -

-----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
-----------------------------------------------------------------------------------------------------------------------
     Called by: ComM
  Precondition: -

  Function to set the inhibition status for to COMM_NO_WAKEUP via the C/S Ports 
**********************************************************************************************************************/
FUNC(Std_ReturnType, COMM_CODE) ComM_ServicePreventWakeUp(ComM_NetworkHandleType Channel, boolean Status)
{

   return ComM_PreventWakeUp((NetworkHandleType)Channel, Status);
}
/*********************************************************************************************************************
FUNCTION: ComM_StateChangeNotification
----------------------------------------------------------------------------------------------------------------------
API     Type                     Name                    Description
----------------------------------------------------------------------------------------------------------------------
  Input: -
  Output: -
  Return: -
----------------------------------------------------------------------------------------------------------------------
  FUNCTION DESCRIPTION
----------------------------------------------------------------------------------------------------------------------
     Called by: upper layer
  Precondition: Communication manager has to be initialized.

  Function to provide user the state change fan out to the higher layers.
*********************************************************************************************************************/
FUNC(void, COMM_CODE) ComM_StateChangeNotification(NetworkHandleType Channel)
{

  Channel = Channel;
}


#define COMM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


