/* -----------------------------------------------------------------------------
  Filename:    Dcm_Lcfg.c
  Description: Generated tables of DCM.
               
               Manufacturer: Vector
               Source file:  C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\System\Haitec_LC.cdd
               EcuDoc:       Nxtr_Common_Manufacturing_Services_CommonDiagnostics
               Variant:      CommonDiagnostics

  Generated by GENy, 2015-08-28 13:52:48 -04:00
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2008-2015 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Includes
 ----------------------------------------------------------------------------- */

#include "Dcm.h"

/* RTE function prototypes */
#include "Rte_Dcm.h"


/* -----------------------------------------------------------------------------
    &&&~ Preprocessor constants (defines)
 ----------------------------------------------------------------------------- */

/* Check the compatibility of the generated files independent from the magic number check. */
#if !defined ( V_SUPPRESS_EXTENDED_VERSION_CHECK )
# if ( DIAG_ASRDCM_IMPLEMENTATION_MAJOR_VERSION != 0x04u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_MAJOR_VERSION with generated file!"
# endif
# if ( DIAG_ASRDCM_IMPLEMENTATION_MINOR_VERSION != 0x07u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_MINOR_VERSION with generated file!"
# endif
# if ( DIAG_ASRDCM_IMPLEMENTATION_PATCH_VERSION != 0x03u)
#  error "Dcm_Lcfg.c : Incompatible DIAG_ASRDCM_IMPLEMENTATION_PATCH_VERSION with generated file!"
# endif
#endif



/* -----------------------------------------------------------------------------
    &&&~ Function prototypes
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

STATIC FUNC(void, DCM_CODE) DcmOnTimeoutDummyCallBack(Dcm_TimerIdType timerId);
STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyGetLength(Dcm_RteDataLenPtrType resDataLenPtr);
#define DCM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Uninitialized RAM 8Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_VAR_NOINIT_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

#if (DCM_DSL_PPRH_SUPPORT_ENABLED == STD_ON) || \
    (DCM_NUM_CONTEXTS > 1)
VAR(uint8, DCM_VAR_NOINIT) dcmPduTransportBuffer[DCM_DSL_CONCUR_BUFF_SIZE_CONST*DCM_DSL_NUM_TRANSP_OBJ_CONST];
#endif

STATIC VAR(uint8, DCM_VAR_NOINIT) dcmProtocolMainBuffer_0[325];
#define DCM_STOP_SEC_VAR_NOINIT_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Uninitialized RAM unspecified definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

VAR(Dcm_TimerCounterType, DCM_VAR_NOINIT)  dcmTimerEngine[DCM_NUM_TIMERS_CONST];

VAR(Dcm_PduRxTransportInfoType, DCM_VAR_NOINIT) dcmPduRxTransportInfo[DCM_DSL_NUM_TRANSP_OBJ_CONST];
#if (DCM_DSL_SHARED_TX_CONN_ENABLED == STD_ON)
VAR(Dcm_PduTxTransportInfoType, DCM_VAR_NOINIT) dcmPduTxTransportInfo[DCM_DSL_NUM_TRANSP_OBJ_CONST];
#endif

/* Global variable of the current DCM state */
VAR(Dcm_StateIdType, DCM_VAR_NOINIT) dcmCurrentStateInfo[2];
VAR(Dcm_MemDidHandleType, DCM_VAR_NOINIT) dcm22_DidList[1][5];
VAR(Dcm_RteDataLenType, DCM_VAR_NOINIT) dcm22_DidResLen[1][5];
/* Global variable of the security access states */
VAR(Dcm_27_SecLevelStateMachineType, DCM_VAR_NOINIT) dcm27_SecLevelStateEngine[1];
#define DCM_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 8Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* StateGroup Session descriptor table */
CONST(uint8, DCM_CONST) dcmStateValuesSession[4] = 
{
  0x01u, 
  0x02u, 
  0x03u, 
  0x7Eu
};
/* StateGroup Security descriptor table */
CONST(uint8, DCM_CONST) dcmStateValuesSecurity[2] = 
{
  0x00u, 
  0x01u
};
/* ServiceId look-up table. */
CONST(uint8, DCM_CONST) dcmDspServiceIdTypeList[10] = 
{
  9, 0x10u, 0x14u, 0x19u, 0x22u, 0x27u, 0x2Eu, 0x2Fu, 0x31u, 0x3Eu
};
/* Session sub-function id look up table */
CONST(uint8, DCM_CONST) dcm10_SubFuncLookUpTable[5] = 
{
  4, 
  0x01u, 
  0x02u, 
  0x03u, 
  0x7Eu
};
/* Read DTC look-up table. */
CONST(uint8, DCM_CONST) dcm19_SubFuncLookUpTable[3] = 
{
  2, 0x01u, 0x02u
};
/* Security access sub-function id look up table */
CONST(uint8, DCM_CONST) dcm27_SubFuncLookUpTable[2] = 
{
  1, 
  0x01u
};
/* Table of 0x2F DIDs' sub-function to control type mapping. */
CONST(uint8, DCM_CONST) dcm2F_SubFuncToCtrlTypeMap[4] = 
{
  0, 2, 2, 1
};
/* Table of 0x31 RIDs' sub-function to control type mapping. */
CONST(uint8, DCM_CONST) dcm31_SubFuncToCtrlTypeMap[4] = 
{
  4, 0, 1, 2
};
#define DCM_STOP_SEC_CONST_8BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 16Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_16BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* DID lookup table */
CONST(uint16, DCM_CONST) dcmDidLookUpTable[50] = 
{
  0x0100u, 0xF180u, 0xF187u, 0xF18Au, 0xF18Cu, 0xF191u, 0xF193u, 0xF194u, 
  0xF195u, 0xFD01u, 0xFD02u, 0xFD07u, 0xFD0Du, 0xFD0Eu, 0xFD10u, 0xFD11u, 
  0xFD12u, 0xFD13u, 0xFD14u, 0xFD17u, 0xFD19u, 0xFD1Au, 0xFD1Bu, 0xFD1Cu, 
  0xFD1Eu, 0xFD20u, 0xFD21u, 0xFD23u, 0xFD25u, 0xFD26u, 0xFD27u, 0xFD29u, 
  0xFD30u, 0xFD31u, 0xFDA1u, 0xFDA2u, 0xFDA3u, 0xFDACu, 0xFDADu, 0xFDAEu, 
  0xFDAFu, 0xFDB0u, 0xFDB1u, 0xFDB2u, 0xFDB3u, 0xFDB4u, 0xFDB5u, 0xFDB6u, 
  0xFDB7u, 0xFE00u
};
/* RID lookup table */
CONST(uint16, DCM_CONST) dcmRidLookUpTable[10] = 
{
    9, 0xF000u, 0xF001u, 0xF003u, 0xF004u, 0xF005u, 0xF008u, 0xF009u, 
  0xF0FFu, 0xFEE0u
};
#define DCM_STOP_SEC_CONST_16BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM 32Bit definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_32BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

#if !defined ( V_SUPPRESS_EXTENDED_VERSION_CHECK )
  CONST(uint32, DCM_CONST) Dcm_GeneratorVersion = (uint32)0x040703;
#endif

#define DCM_STOP_SEC_CONST_32BIT
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ ROM unspecified definitions
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

/* Context management */
#if (DCM_NUM_CONTEXTS > 1)
CONST(Dcm_MemTimerIdType, DCM_CONST) dcmTmrMgrContextP2TimerId[DCM_NUM_CONTEXTS] =
{
  DCM_TIMER_ID_P2_CONST,      /* UDS P2 Timer */
  DCM_TIMER_ID_OBD_P2_CONST   /* OBD P2 Timer */
};
#endif

/* Timer manager timeout notification callback table. */
CONST(Dcm_TimerTimeoutCallBackType, DCM_CONST) dcmTimerManagerInfo[4] = 
{
  DcmOnTimeoutSession, 
  DcmOnTimeoutResponsePending, 
  DcmOnTimeoutDummyCallBack, 
  DcmOnTimeoutDummyCallBack
};
/* RxPduIds property table. */
CONST(Dcm_RxPduInfoType, DCM_CONST) dcmDslRxPduInfoTable[2] = 
{
  { 0 }, 
  { 1 }
};
/* RxPduId mapping to connection */
CONST(Dcm_ConnectionRefType, DCM_CONST) dcmDslRxPdu2ConnMap[2][1] = 
{
  { 0 }, 
  { 0 }
};
/* TxPduIds connection reference table. */
CONST(Dcm_ConnectionRefType, DCM_CONST) dcmTxPduToConnTable[1] = 
{
  0
};
/* PDU connections property table. */
CONST(Dcm_PduConnectionType, DCM_CONST) dcmDslPduConnectionInfoTable[1] = 
{
  { 0, 0x72u, 0, 0, 0, 0, 4095, NULL_PTR }
};
/* PDU protocols property table. */
CONST(Dcm_PduProtocolType, DCM_CONST) dcmDslPduProtocolInfoTable[1] = 
{
  { { 0, 0 }, { 0, 0 }, 325, dcmProtocolMainBuffer_0, NULL_PTR, NULL_PTR }
};
/* Service execution state-filter pool */
CONST(Dcm_StateMaskType, DCM_CONST) dcmServiceStateFilterPool[6][2] = 
{
  { 0x0Fu, 0x03u }, 
  { 0x0Du, 0x03u }, 
  { 0x0Cu, 0x03u }, 
  { 0x0Au, 0x03u }, 
  { 0x08u, 0x03u }, 
  { 0x0Eu, 0x03u }
};
/* Service transition precondition state pool */
CONST(Dcm_StateMaskType, DCM_CONST) dcmStateTransPrecondInfo[6][2] = 
{
  { 0x0Fu, 0x02u }, 
  { 0x0Fu, 0x02u }, 
  { 0x0Du, 0x02u }, 
  { 0x0Du, 0x02u }, 
  { 0x00u, 0x00u }, 
  { 0x00u, 0x01u }
};
/* Service transition target state index pool */
CONST(Dcm_StateIdType, DCM_CONST) dcmStateTransTargetInfo[6][2] = 
{
  {   0,   0 }, 
  {   1,   0 }, 
  {   2,   0 }, 
  {   3,   0 }, 
  {   0,   0 }, 
  {   0,   1 }
};
/* StateGroup descriptor table */
CONST(Dcm_StateGroupInfoType, DCM_CONST) dcmStateGroupInfo[2] = 
{
  { 4, 0x7Fu, dcmStateValuesSession, DcmOnChgStateSession }, 
  { 2, 0x33u, dcmStateValuesSecurity, DcmOnChgStateSecurity }
};
/* ServiceId property table. */
CONST(Dcm_ServiceTableType, DCM_CONST) dcmDspServiceInfoTable[10] = 
{
  { 0x1Fu, 2, 2, 0, Dcm_DspDiagSessionControl, Dcm_DspInitDummyService, Dcm_DspPostDiagSessionControl } /* 0x10 */, 
  { 0x0Fu, 4, 4, 1, Dcm_DspClearDiagInfo, Dcm_DspInitDummyService, Dcm_DspPostClearDiagInfo } /* 0x14 */, 
  { 0x1Fu, 2, 0, 1, Dcm_DspReadDtcInfo, Dcm_DspInitDummyService, Dcm_DspPostReadDtcInfo } /* 0x19 */, 
  { 0x0Fu, 3, 0, 0, Dcm_DspReadDataById, Dcm_DspInitReadDataById, Dcm_DspPostReadDataById } /* 0x22 */, 
  { 0x15u, 2, 0, 5, Dcm_DspSecurityAccess, Dcm_DspInitSecurityAccess, Dcm_DspPostSecurityAccess } /* 0x27 */, 
  { 0x0Fu, 4, 0, 0, Dcm_DspWriteDataById, Dcm_DspInitWriteDataById, Dcm_DspPostWriteDataById } /* 0x2e */, 
  { 0x0Fu, 4, 0, 0, Dcm_DspIoControlById, Dcm_DspInitDummyService, Dcm_DspPostDummyService } /* 0x2f */, 
  { 0x15u, 4, 0, 0, Dcm_DspRoutineControl, Dcm_DspInitRoutineControl, Dcm_DspPostDummyService } /* 0x31 */, 

  { 0x1Fu, 2, 2, 0, Dcm_DspTesterPresent, Dcm_DspInitDummyService, Dcm_DspPostDummyService } /* 0x3e */, 
  { 0x0Fu, 1, 0, 0, Dcm_DspUnknownService, Dcm_DspInitDummyService, Dcm_DspPostUnknownService } /* 0xff */
};
/* Session control information table. */
CONST(Dcm_SessionControlInfoType, DCM_CONST) dcm10_ServiceInfoTable[4] = 
{
  { { 50, 500 }, { 5, 500 }, 0, 0 } /* SubFuncId: 0x01 */, 
  { { 50, 500 }, { 5, 500 }, 0, 1 } /* SubFuncId: 0x02 */, 
  { { 50, 500 }, { 5, 500 }, 1, 2 } /* SubFuncId: 0x03 */, 
  { { 50, 500 }, { 5, 500 }, 1, 3 } /* SubFuncId: 0x7e */
};
CONST(Dcm_10_RteChgPermCallBackType, DCM_CONST) dcm10_SesChgPermFunc = Rte_Call_SessionControl_GetSesChgPermission;
CONST(Dcm_10_RteChgIndCallBackType, DCM_CONST) dcm10_SesChgIndFunc = Rte_Call_SessionControl_ChangeIndication;
CONST(Dcm_10_RteRcrRpConfCallBackType, DCM_CONST) dcm10_RcrRpConfFunc = Rte_Call_SessionControl_ConfirmationRespPending;
/* Read DTC property table. */
CONST(Dcm_19_SubFunctionInfoType, DCM_CONST) dcm19_ServiceInfoTable[2] = 
{
  { 0x02u, 1, 1, Dcm_DspReadDtcRNODTCBSM } /* SubFuncId: 0x01 */, 
  { 0x02u, 1, 1, Dcm_DspReadDtcRDTCBSM } /* SubFuncId: 0x02 */
};
/* Service 0x22 DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm22_DidStateInfoTable[50] = 
{
   2 /* DID: 0x0100 */, 
   3 /* DID: 0xf180 */, 
   0 /* DID: 0xf187 */, 
   0 /* DID: 0xf18a */, 
   0 /* DID: 0xf18c */, 
   3 /* DID: 0xf191 */, 
   0 /* DID: 0xf193 */, 
   0 /* DID: 0xf194 */, 
   0 /* DID: 0xf195 */, 
   0 /* DID: 0xfd01 */, 
   0 /* DID: 0xfd02 */, 
   0 /* DID: 0xfd07 */, 
   0 /* DID: 0xfd0d */, 
   0 /* DID: 0xfd0e */, 
   0 /* DID: 0xfd10 */, 
   0 /* DID: 0xfd11 */, 
   0 /* DID: 0xfd12 */, 
   0 /* DID: 0xfd13 */, 
   0 /* DID: 0xfd14 */, 
   0 /* DID: 0xfd17 */, 
   0 /* DID: 0xfd19 */, 
   0 /* DID: 0xfd1a */, 
   0 /* DID: 0xfd1b */, 
   0 /* DID: 0xfd1c */, 
   0 /* DID: 0xfd1e */, 
   0 /* DID: 0xfd20 */, 
   0 /* DID: 0xfd21 */, 
   0 /* DID: 0xfd23 */, 
   0 /* DID: 0xfd25 */, 
   0 /* DID: 0xfd26 */, 
   0 /* DID: 0xfd27 */, 
   0 /* DID: 0xfd29 */, 
   0 /* DID: 0xfd30 */, 
   0 /* DID: 0xfd31 */, 
   0 /* DID: 0xfda1 */, 
   0 /* DID: 0xfda2 */, 
   0 /* DID: 0xfda3 */, 
   0 /* DID: 0xfdac */, 
   0 /* DID: 0xfdad */, 
   0 /* DID: 0xfdae */, 
   0 /* DID: 0xfdaf */, 
   0 /* DID: 0xfdb0 */, 
   0 /* DID: 0xfdb1 */, 
   0 /* DID: 0xfdb2 */, 
   0 /* DID: 0xfdb3 */, 
   0 /* DID: 0xfdb4 */, 
   0 /* DID: 0xfdb5 */, 
   0 /* DID: 0xfdb6 */, 
   0 /* DID: 0xfdb7 */, 
   0 /* DID: 0xfe00 */
};
/* Service 0x22 DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm22_DidHandleTable[51] = 
{
   50 /* Total size of the lookup table */, 
    0 /* DID: 0x0100 */, 
    1 /* DID: 0xf180 */, 
    2 /* DID: 0xf187 */, 
    3 /* DID: 0xf18a */, 
    4 /* DID: 0xf18c */, 
    5 /* DID: 0xf191 */, 
    6 /* DID: 0xf193 */, 
    7 /* DID: 0xf194 */, 
    8 /* DID: 0xf195 */, 
    9 /* DID: 0xfd01 */, 
   10 /* DID: 0xfd02 */, 
   11 /* DID: 0xfd07 */, 
   12 /* DID: 0xfd0d */, 
   13 /* DID: 0xfd0e */, 
   14 /* DID: 0xfd10 */, 
   15 /* DID: 0xfd11 */, 
   16 /* DID: 0xfd12 */, 
   17 /* DID: 0xfd13 */, 
   18 /* DID: 0xfd14 */, 
   19 /* DID: 0xfd17 */, 
   20 /* DID: 0xfd19 */, 
   21 /* DID: 0xfd1a */, 
   22 /* DID: 0xfd1b */, 
   23 /* DID: 0xfd1c */, 
   24 /* DID: 0xfd1e */, 
   25 /* DID: 0xfd20 */, 
   26 /* DID: 0xfd21 */, 
   27 /* DID: 0xfd23 */, 
   28 /* DID: 0xfd25 */, 
   29 /* DID: 0xfd26 */, 
   30 /* DID: 0xfd27 */, 
   31 /* DID: 0xfd29 */, 
   32 /* DID: 0xfd30 */, 
   33 /* DID: 0xfd31 */, 
   34 /* DID: 0xfda1 */, 
   35 /* DID: 0xfda2 */, 
   36 /* DID: 0xfda3 */, 
   37 /* DID: 0xfdac */, 
   38 /* DID: 0xfdad */, 
   39 /* DID: 0xfdae */, 
   40 /* DID: 0xfdaf */, 
   41 /* DID: 0xfdb0 */, 
   42 /* DID: 0xfdb1 */, 
   43 /* DID: 0xfdb2 */, 
   44 /* DID: 0xfdb3 */, 
   45 /* DID: 0xfdb4 */, 
   46 /* DID: 0xfdb5 */, 
   47 /* DID: 0xfdb6 */, 
   48 /* DID: 0xfdb7 */, 
   49 /* DID: 0xfe00 */
};
/* Service 0x22 DID property table */
CONST(Dcm_22_ServiceInfoType, DCM_CONST) dcm22_ServiceInfoTable[50] = 
{
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0x0100_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0x0100_ReadData } /* 0x0100 */, 
  { 25, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf180_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf180_ReadData } /* 0xf180 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf187_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf187_ReadData } /* 0xf187 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf18a_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf18a_ReadData } /* 0xf18a */, 
  { 16, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf18c_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf18c_ReadData } /* 0xf18c */, 
  { 16, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf191_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf191_ReadData } /* 0xf191 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf193_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf193_ReadData } /* 0xf193 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf194_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf194_ReadData } /* 0xf194 */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xf195_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xf195_ReadData } /* 0xf195 */, 
  { 322, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd01_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd01_ReadData } /* 0xfd01 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd02_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd02_ReadData } /* 0xfd02 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd07_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd07_ReadData } /* 0xfd07 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd0d_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd0d_ReadData } /* 0xfd0d */, 
  {  8, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd0e_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd0e_ReadData } /* 0xfd0e */, 
  { 10, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd10_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd10_ReadData } /* 0xfd10 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd11_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd11_ReadData } /* 0xfd11 */, 
  { 28, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd12_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd12_ReadData } /* 0xfd12 */, 
  { 75, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd13_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd13_ReadData } /* 0xfd13 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd14_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd14_ReadData } /* 0xfd14 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd17_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd17_ReadData } /* 0xfd17 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd19_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd19_ReadData } /* 0xfd19 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1a_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1a_ReadData } /* 0xfd1a */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1b_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1b_ReadData } /* 0xfd1b */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1c_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1c_ReadData } /* 0xfd1c */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd1e_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd1e_ReadData } /* 0xfd1e */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd20_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd20_ReadData } /* 0xfd20 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd21_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd21_ReadData } /* 0xfd21 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd23_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd23_ReadData } /* 0xfd23 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd25_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd25_ReadData } /* 0xfd25 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd26_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd26_ReadData } /* 0xfd26 */, 
  {  1, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd27_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd27_ReadData } /* 0xfd27 */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd29_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd29_ReadData } /* 0xfd29 */, 
  {  5, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd30_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd30_ReadData } /* 0xfd30 */, 
  { 12, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfd31_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfd31_ReadData } /* 0xfd31 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda1_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda1_ReadData } /* 0xfda1 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda2_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda2_ReadData } /* 0xfda2 */, 
  { 12, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfda3_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfda3_ReadData } /* 0xfda3 */, 
  { 64, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdac_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdac_ReadData } /* 0xfdac */, 
  {  7, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdad_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdad_ReadData } /* 0xfdad */, 
  {  2, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdae_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdae_ReadData } /* 0xfdae */, 
  { 176, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdaf_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdaf_ReadData } /* 0xfdaf */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb0_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb0_ReadData } /* 0xfdb0 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb1_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb1_ReadData } /* 0xfdb1 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb2_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb2_ReadData } /* 0xfdb2 */, 
  { 256, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb3_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb3_ReadData } /* 0xfdb3 */, 
  {  8, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb4_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb4_ReadData } /* 0xfdb4 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb5_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb5_ReadData } /* 0xfdb5 */, 
  {  4, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb6_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb6_ReadData } /* 0xfdb6 */, 
  { 18, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfdb7_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfdb7_ReadData } /* 0xfdb7 */, 
  {  3, (Dcm_RteCheckReadDidCallBackType)Rte_Call_DidServices_0xfe00_ConditionCheckRead, (Dcm_RteGetReadDidLenCallBackType)Dcm_22_DummyGetLength, (Dcm_RteReadDidCallBackType)Rte_Call_DidServices_0xfe00_ReadData } /* 0xfe00 */
};
/* Security access property table. */
CONST(Dcm_SecAccessTableType, DCM_CONST) dcm27_ServiceInfoTable[1] = 
{
  { 3, 3, 3, 3, 0, 5, 5, 4, 5, 1000, 0, (Dcm_RteGetSeedCallBackType)Rte_Call_SecurityAccess_1_GetSeed, (Dcm_RteSendKeyCallBackType)Rte_Call_SecurityAccess_1_CompareKey } /* SubFuncId: 0x01 */
};
/* Service 0x2E DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2E_DidStateInfoTable[29] = 
{
   2 /* DID: 0x0100 */, 
   4 /* DID: 0xf187 */, 
   4 /* DID: 0xf18a */, 
   0 /* DID: 0xfd02 */, 
   0 /* DID: 0xfd07 */, 
   0 /* DID: 0xfd12 */, 
   0 /* DID: 0xfd19 */, 
   0 /* DID: 0xfd1b */, 
   0 /* DID: 0xfd1e */, 
   0 /* DID: 0xfd21 */, 
   0 /* DID: 0xfd23 */, 
   0 /* DID: 0xfd25 */, 
   0 /* DID: 0xfd26 */, 
   0 /* DID: 0xfd27 */, 
   0 /* DID: 0xfd29 */, 
   0 /* DID: 0xfd30 */, 
   0 /* DID: 0xfda1 */, 
   0 /* DID: 0xfda2 */, 
   0 /* DID: 0xfda3 */, 
   0 /* DID: 0xfdac */, 
   0 /* DID: 0xfdae */, 
   0 /* DID: 0xfdb0 */, 
   0 /* DID: 0xfdb1 */, 
   0 /* DID: 0xfdb2 */, 
   0 /* DID: 0xfdb3 */, 
   0 /* DID: 0xfdb4 */, 
   0 /* DID: 0xfdb5 */, 
   0 /* DID: 0xfdb6 */, 
   0 /* DID: 0xfdb7 */
};
/* Service 0x2E DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm2E_DidHandleTable[30] = 
{
   29 /* Total size of the lookup table */, 
    0 /* DID: 0x0100 */, 
    2 /* DID: 0xf187 */, 
    3 /* DID: 0xf18a */, 
   10 /* DID: 0xfd02 */, 
   11 /* DID: 0xfd07 */, 
   16 /* DID: 0xfd12 */, 
   20 /* DID: 0xfd19 */, 
   22 /* DID: 0xfd1b */, 
   24 /* DID: 0xfd1e */, 
   26 /* DID: 0xfd21 */, 
   27 /* DID: 0xfd23 */, 
   28 /* DID: 0xfd25 */, 
   29 /* DID: 0xfd26 */, 
   30 /* DID: 0xfd27 */, 
   31 /* DID: 0xfd29 */, 
   32 /* DID: 0xfd30 */, 
   34 /* DID: 0xfda1 */, 
   35 /* DID: 0xfda2 */, 
   36 /* DID: 0xfda3 */, 
   37 /* DID: 0xfdac */, 
   39 /* DID: 0xfdae */, 
   41 /* DID: 0xfdb0 */, 
   42 /* DID: 0xfdb1 */, 
   43 /* DID: 0xfdb2 */, 
   44 /* DID: 0xfdb3 */, 
   45 /* DID: 0xfdb4 */, 
   46 /* DID: 0xfdb5 */, 
   47 /* DID: 0xfdb6 */, 
   48 /* DID: 0xfdb7 */
};
/* Service 0x2E DID property table */
CONST(Dcm_2E_ServiceInfoType, DCM_CONST) dcm2E_ServiceInfoTable[29] = 
{
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0x0100_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0x0100_WriteData } /* 0x0100 */, 
  { 10, 10, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf187_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf187_WriteData } /* 0xf187 */, 
  { 10, 10, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xf18a_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xf18a_WriteData } /* 0xf18a */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd02_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd02_WriteData } /* 0xfd02 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd07_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd07_WriteData } /* 0xfd07 */, 
  { 28, 28, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd12_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd12_WriteData } /* 0xfd12 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd19_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd19_WriteData } /* 0xfd19 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd1b_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd1b_WriteData } /* 0xfd1b */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd1e_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd1e_WriteData } /* 0xfd1e */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd21_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd21_WriteData } /* 0xfd21 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd23_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd23_WriteData } /* 0xfd23 */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd25_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd25_WriteData } /* 0xfd25 */, 
  {  3,  3, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd26_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd26_WriteData } /* 0xfd26 */, 
  {  1,  1, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd27_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd27_WriteData } /* 0xfd27 */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd29_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd29_WriteData } /* 0xfd29 */, 
  {  5,  5, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfd30_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfd30_WriteData } /* 0xfd30 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda1_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda1_WriteData } /* 0xfda1 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda2_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda2_WriteData } /* 0xfda2 */, 
  { 12, 12, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfda3_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfda3_WriteData } /* 0xfda3 */, 
  { 64, 64, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdac_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdac_WriteData } /* 0xfdac */, 
  {  2,  2, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdae_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdae_WriteData } /* 0xfdae */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb0_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb0_WriteData } /* 0xfdb0 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb1_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb1_WriteData } /* 0xfdb1 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb2_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb2_WriteData } /* 0xfdb2 */, 
  { 256, 256, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb3_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb3_WriteData } /* 0xfdb3 */, 
  {  8,  8, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb4_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb4_WriteData } /* 0xfdb4 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb5_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb5_WriteData } /* 0xfdb5 */, 
  {  4,  4, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb6_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb6_WriteData } /* 0xfdb6 */, 
  { 18, 18, (Dcm_RteCheckWriteDidCallBackType)Rte_Call_DidServices_0xfdb7_ConditionCheckWrite, (Dcm_RteWriteDidCallBackType)Rte_Call_DidServices_0xfdb7_WriteData } /* 0xfdb7 */
};
/* Service 0x2F DID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2F_DidStateInfoTable[3] = 
{
   0 /* DID: 0xfd0d */, 
   0 /* DID: 0xfd11 */, 
   0 /* DID: 0xfe00 */
};
/* Service 0x2F DID and ControlOp state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm2F_SubFuncStateInfoTable[6] = 
{
   0,  0,  0,  0,  0,  0
};
/* Service 0x2F DID lookup table */
CONST(Dcm_MemDidHandleType, DCM_CONST) dcm2F_DidHandleTable[4] = 
{
    3 /* Total size of the lookup table */, 
   12 /* DID: 0xfd0d */, 
   15 /* DID: 0xfd11 */, 
   49 /* DID: 0xfe00 */
};
/* Service 0x2F DID property table */
CONST(Dcm_2F_ServiceInfoType, DCM_CONST) dcm2F_ServiceInfoTable[6] = 
{
  {  0,  0,  2, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd0d_ReturnControlToECU } /* DID: 0xfd0d */, 
  {  2,  2,  2, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd0d_ShortTermAdjustment } /* DID: 0xfd0d */, 
  {  0,  0,  2, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd11_ReturnControlToECU } /* DID: 0xfd11 */, 
  {  2,  2,  2, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfd11_ShortTermAdjustment } /* DID: 0xfd11 */, 
  {  0,  0,  3, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfe00_ReturnControlToECU } /* DID: 0xfe00 */, 
  {  3,  3,  3, (Dcm_RteIoCtrlDidCallBackType)Rte_Call_DidServices_0xfe00_ShortTermAdjustment } /* DID: 0xfe00 */
};
/* Table of 0x2F DID to sub-function mapping. */
CONST(Dcm_2F_MemInstHandleType, DCM_CONST) dcm2F_DidControlTypeInfo[3][2] = 
{
  {    0,    1 } /* DID: 0xfd0d */, 
  {    2,    3 } /* DID: 0xfd11 */, 
  {    4,    5 } /* DID: 0xfe00 */
};
/* Service 0x31 RID state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm31_RidStateInfoTable[9] = 
{
   0 /* RID: 0xf000 */, 
   0 /* RID: 0xf001 */, 
   0 /* RID: 0xf003 */, 
   0 /* RID: 0xf004 */, 
   0 /* RID: 0xf005 */, 
   0 /* RID: 0xf008 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf0ff */, 
   5 /* RID: 0xfee0 */
};
/* Service 0x31 RID and ControlOp state filter table */
CONST(Dcm_StateFilterIndexType, DCM_CONST) dcm31_SubFuncStateInfoTable[11] = 
{
   0 /* RID: 0xf000 */, 
   0 /* RID: 0xf001 */, 
   0 /* RID: 0xf003 */, 
   0 /* RID: 0xf004 */, 
   0 /* RID: 0xf005 */, 
   0 /* RID: 0xf008 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf009 */, 
   0 /* RID: 0xf0ff */, 
   5 /* RID: 0xfee0 */
};
/* Service 0x31 RID property table */
CONST(Dcm_31_ServiceInfoType, DCM_CONST) dcm31_ServiceInfoTable[11] = 
{
  {  3,  3,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf000_Start } /* RID: 0xf000 */, 
  {  2,  2,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf001_Start } /* RID: 0xf001 */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf003_Start } /* RID: 0xf003 */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf004_Start } /* RID: 0xf004 */, 
  {  2,  2,  3, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf005_Start } /* RID: 0xf005 */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf008_Start } /* RID: 0xf008 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_Start } /* RID: 0xf009 */, 
  {  0,  0,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_Stop } /* RID: 0xf009 */, 

  {  0,  0,  1, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf009_RequestResults } /* RID: 0xf009 */, 
  {  6,  6,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xf0ff_Start } /* RID: 0xf0ff */, 
  {  1,  1,  0, (Dcm_RteCtrlRidCallBackType)Rte_Call_RoutineServices_0xfee0_Start } /* RID: 0xfee0 */
};
/* Table of 0x31 RID to sub-function mapping. */
CONST(Dcm_MemRidInstHandleType, DCM_CONST) dcm31_ControlTypeInfo[9][3] = 
{
  {    0,   11,   11 } /* RID: 0xf000 */, 
  {    1,   11,   11 } /* RID: 0xf001 */, 
  {    2,   11,   11 } /* RID: 0xf003 */, 
  {    3,   11,   11 } /* RID: 0xf004 */, 
  {    4,   11,   11 } /* RID: 0xf005 */, 
  {    5,   11,   11 } /* RID: 0xf008 */, 
  {    6,    7,    8 } /* RID: 0xf009 */, 
  {    9,   11,   11 } /* RID: 0xf0ff */, 

  {   10,   11,   11 } /* RID: 0xfee0 */
};
#define DCM_STOP_SEC_CONST_UNSPECIFIED
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



/* -----------------------------------------------------------------------------
    &&&~ Internal implementation
 ----------------------------------------------------------------------------- */

#define DCM_START_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */

STATIC FUNC(void, DCM_CODE) DcmOnTimeoutDummyCallBack(Dcm_TimerIdType timerId)
{
  DCM_IGNORE_UNREF_PARAM(timerId); /* PRQA S 3112 */ /* Avoid warnings on specific API implementation */
}


STATIC FUNC(Std_ReturnType, DCM_CODE) Dcm_22_DummyGetLength(Dcm_RteDataLenPtrType resDataLenPtr) /* PRQA S 3673 */ /* AUTOSAR defined interface */
{
  DCM_IGNORE_UNREF_PARAM(resDataLenPtr); /* PRQA S 3112 */ /* Avoid warnings on specific API implementation */
  return DCM_E_NOT_OK;
}


#define DCM_STOP_SEC_CODE
#include "MemMap.h" /* PRQA S 5087 */ /* MD_MSR_19.1 */



