/* -----------------------------------------------------------------------------
  Filename:    PduR_PBcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2015-02-13  10:21:39
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ Include Section
 ----------------------------------------------------------------------------- */

#include "PduR.h"


#define PDUR_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Post-Build PduR Configuration Structure
 ----------------------------------------------------------------------------- */

CONST(PduR_PBConfigType, PDUR_PBCFG) PduRGlobalConfig = 
{
  (PduIdType) 3 /* Current Number of Rx CanIf Lo RX PDUs 2 Upper Layers. */, 
  PduR_CfgTblRxCanIf2UpPduRGlobalConfig /* Pointer to the RX routing table of Rx CanIf Lo */, 
  (PduIdType) 6, 
  PduR_CfgTblTxCanIf2UpPduRGlobalConfig /* Pointer to the TX routing table of Tx CanIf Lo */, 
  (PduIdType) 2 /* Current Number of Rx CanTp Lo RX PDUs 2 Upper Layers. */, 
  PduR_CfgTblRxCanTp2UpPduRGlobalConfig /* Pointer to the RX routing table of Rx CanTp Lo */, 
  (PduIdType) 1, 
  PduR_CfgTblTxCanTp2UpPduRGlobalConfig /* Pointer to the TX routing table of Tx CanTp Lo */, 
  (PduIdType) 2, 
  PduR_CfgTblTxCom2LoPduRGlobalConfig /* Pointer to the RX routing table of Tx Com Up */, 
  (PduIdType) 1, 
  PduR_CfgTblTxDcm2LoPduRGlobalConfig /* Pointer to the RX routing table of Tx Dcm Up */
};



#define PDUR_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Routing Tables
 ----------------------------------------------------------------------------- */

CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblRxCanIf2UpPduRGlobalConfig[3] = 
{
  { (PduR_Core_PortIdType) 0x05, (PduIdType) 1 } /* Source Id: 0 - I-PDU: BCM1__CAN00 - Target Port: Rx Com Up - Dest Pdu: Pdu_BCM1__CAN00 */, 
  { (PduR_Core_PortIdType) 0x05, (PduIdType) 0 } /* Source Id: 1 - I-PDU: ABS2__CAN00 - Target Port: Rx Com Up - Dest Pdu: Pdu_ABS2__CAN00 */, 
  { (PduR_Core_PortIdType) 0x05, (PduIdType) 2 } /* Source Id: 2 - I-PDU: ECM1__CAN00 - Target Port: Rx Com Up - Dest Pdu: Pdu_ECM1__CAN00 */
};
CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblRxCanTp2UpPduRGlobalConfig[2] = 
{
  { (PduR_Core_PortIdType) 0x06, (PduIdType) 1 } /* Source Id: 0 - I-PDU: DiagFuncReqFT__CAN00 - Target Port: Rx Dcm Up - Dest Pdu: DiagFuncReqFT__CAN00 */, 
  { (PduR_Core_PortIdType) 0x06, (PduIdType) 0 } /* Source Id: 1 - I-PDU: DiagPhysReqToEPAS__CAN00_EPAS - Target Port: Rx Dcm Up - Dest Pdu: DiagPhysReqToEPAS__CAN00_EPAS */
};
CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblTxCanIf2UpPduRGlobalConfig[6] = 
{
  { (PduR_Core_PortIdType) 0x0B, (PduIdType) 0 } /* Source Id: 0 - I-PDU: GliwaSlave__CAN00 - Target Port: Invalid */, 
  { (PduR_Core_PortIdType) 0x0B, (PduIdType) 0 } /* Source Id: 1 - I-PDU: DiagRespFromEPAS_Tp__CAN00 - Target Port: Invalid */, 
  { (PduR_Core_PortIdType) 0x0B, (PduIdType) 0 } /* Source Id: 2 - I-PDU: NMmEPAS__CAN00 - Target Port: Invalid */, 
  { (PduR_Core_PortIdType) 0x0B, (PduIdType) 0 } /* Source Id: 3 - I-PDU: XcpSlave__CAN00 - Target Port: Invalid */, 
  { (PduR_Core_PortIdType) 0x05, (PduIdType) 0 } /* Source Id: 4 - I-PDU: EPAS2__CAN00 - Target Port: Tx Com Up - Dest Pdu: Pdu_EPAS2__CAN00 */, 
  { (PduR_Core_PortIdType) 0x05, (PduIdType) 1 } /* Source Id: 5 - I-PDU: EPAS1__CAN00 - Target Port: Tx Com Up - Dest Pdu: Pdu_EPAS1__CAN00 */
};
CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblTxCanTp2UpPduRGlobalConfig[1] = 
{
  { (PduR_Core_PortIdType) 0x06, (PduIdType) 0 } /* Source Id: 0 - I-PDU: DiagRespFromEPAS__CAN00 - Target Port: Tx Dcm Up - Dest Pdu: DiagRespFromEPAS__CAN00 */
};
CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblTxCom2LoPduRGlobalConfig[2] = 
{
  { (PduR_Core_PortIdType) 0x02, (PduIdType) 4 } /* Source Id: 0 - I-PDU: Pdu_EPAS2__CAN00 - Target Port: Tx CanIf Lo - Dest Pdu: EPAS2__CAN00 */, 
  { (PduR_Core_PortIdType) 0x02, (PduIdType) 5 } /* Source Id: 1 - I-PDU: Pdu_EPAS1__CAN00 - Target Port: Tx CanIf Lo - Dest Pdu: EPAS1__CAN00 */
};
CONST(PduR_Core_DestInfoType, PDUR_PBCFG) PduR_CfgTblTxDcm2LoPduRGlobalConfig[1] = 
{
  { (PduR_Core_PortIdType) 0x04, (PduIdType) 0 } /* Source Id: 0 - I-PDU: DiagRespFromEPAS__CAN00 - Target Port: Tx CanTp Lo - Dest Pdu: DiagRespFromEPAS__CAN00 */
};




#define PDUR_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



