/* -----------------------------------------------------------------------------
  Filename:    PduR_PBcfg.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\Temp\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-07-19  08:51:13
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_PBCFG_H)
#define PDUR_PBCFG_H

#define PDUR_START_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* Contains all configuration data or references to it that can be changed at post-build time if Configuration Variant 3 is used. */
extern CONST(PduR_PBConfigType, PDUR_PBCFG) PduRGlobalConfig;



#define PDUR_STOP_SEC_PBCFG_ROOT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#define PDUR_START_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

/* -----------------------------------------------------------------------------
    &&&~ Routing Tables
 ----------------------------------------------------------------------------- */

/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblRxCanIf2UpPduRGlobalConfig[];
/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblRxCanTp2UpPduRGlobalConfig[];
/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblTxCanIf2UpPduRGlobalConfig[];
/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblTxCanTp2UpPduRGlobalConfig[];
/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblTxCom2LoPduRGlobalConfig[];
/* PRQA  S 3684 1 *//* RULE 8.12: When an array is declared with external linkage, its size shall be stated explicitly or defined implicitly by initialisation */
extern CONST(PduR_Core_DestInfoType, PDUR_CONST) PduR_CfgTblTxDcm2LoPduRGlobalConfig[];



#define PDUR_STOP_SEC_PBCFG
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




#endif /* PDUR_PBCFG_H */
