/* -----------------------------------------------------------------------------
  Filename:    PduR_Lcfg.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\Temp\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-07-19  08:51:13
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_LCFG_H)
#define PDUR_LCFG_H

/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA TYPES AND STRUCTURES
 ----------------------------------------------------------------------------- */

#define PDUR_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

extern CONST(PduR_Core_TransmitFctPtrType, PDUR_PBCFG) PduR_Core_TransmitFctPtrTbl[21];
extern CONST(PduR_UpIfTriggerTransmitFctPtrType, PDUR_PBCFG) PduR_Core_UpIfTriggerTransmit[21];
extern CONST(PduR_UpIfTxConfirmationFctPtrType, PDUR_PBCFG) PduR_Core_UpIfTxConfirmation[21];
extern CONST(PduR_UpIfRxIndicationFctPtrType, PDUR_PBCFG) PduR_Core_UpIfRxIndication[21];
extern CONST(PduR_UpTpProvideTxBufferFctPtrType, PDUR_PBCFG) PduR_Core_UpTpProvideTxBuffer[21];
extern CONST(PduR_UpTpTxConfirmationFctPtrType, PDUR_PBCFG) PduR_Core_UpTpTxConfirmation[21];
extern CONST(PduR_UpTpRxIndicationFctPtrType, PDUR_PBCFG) PduR_Core_UpTpRxIndication[21];
extern CONST(PduR_UpTpProvideRxBufferFctPtrType, PDUR_PBCFG) PduR_Core_UpTpProvideRxBuffer[21];
#define PDUR_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

#define PDUR_START_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"

#define PDUR_STOP_SEC_VAR_NOINIT_UNSPECIFIED
/* PRQA S 5087 1 */ /* RULE 19.1: The memory abstraction concept uses includes of MemMap.h at any place in the source code. This is required by AUTOSAR. */
#include "MemMap.h"




#endif /* PDUR_LCFG_H */
