/* -----------------------------------------------------------------------------
  Filename:    PduR_Types.h
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: PduR
               
               Configuration   : C:\Temp\Haitec_LC_EPS_TMS570\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-07-19  08:51:13
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

#if !defined(PDUR_TYPES_H)
#define PDUR_TYPES_H

/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "ComStack_Types.h"
#include "v_cfg.h"
#include "v_def.h"


/* -----------------------------------------------------------------------------
    &&&~ GLOBAL CONSTANT MACROS
 ----------------------------------------------------------------------------- */

#if (PDUR_USE_PDUINFOTYPE == STD_ON)
#define PDUR_TRIGGERTRANSMIT_PARA            PduInfoPtr
#define PDUR_TRIGGERTRANSMIT_DATAPTR         (PduInfoPtr->SduDataPtr)
#define PDUR_TRIGGERTRANSMIT_TYPE            CONSTP2VAR(PduInfoType, AUTOMATIC, PDUR_APPL_DATA)
#define PDUR_TRIGGERTRANSMIT_RETURN          Std_ReturnType
#define PDUR_TRIGGERTRANSMIT_OK              E_OK
#define PDUR_TRIGGERTRANSMIT_NOK             E_NOT_OK
#define PDUR_RXINDICATION_PARA               PduInfoPtr
#define PDUR_RXINDICATION_DATAPTR            (PduInfoPtr->SduDataPtr)
#define PDUR_RXINDICATION_TYPE               P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA)
#else
#define PDUR_TRIGGERTRANSMIT_PARA            SduPtr
#define PDUR_TRIGGERTRANSMIT_DATAPTR         ((SduDataPtrType)SduPtr)
#define PDUR_TRIGGERTRANSMIT_TYPE            CONSTP2VAR(uint8, AUTOMATIC, PDUR_APPL_DATA)
#define PDUR_TRIGGERTRANSMIT_RETURN          void
#define PDUR_TRIGGERTRANSMIT_OK
#define PDUR_TRIGGERTRANSMIT_NOK
#define PDUR_RXINDICATION_PARA               SduPtr
#define PDUR_RXINDICATION_DATAPTR            ((SduDataPtrType)SduPtr)
#define PDUR_RXINDICATION_TYPE               P2CONST(uint8, AUTOMATIC, PDUR_APPL_DATA)
#endif



/* -----------------------------------------------------------------------------
    &&&~ GLOBAL DATA TYPES AND STRUCTURES
 ----------------------------------------------------------------------------- */

typedef VAR(vbittype, PDUR_VAR_NOINIT) PduR_Core_BitType; /* Type for bit fields */
typedef P2VAR(PduInfoType, TYPEDEF, PDUR_APPL_DATA) PduInfoTypeApplPtr; /* Helper type for compiler abstraction */
typedef VAR(uint8, PDUR_VAR_NOINIT) PduR_Core_PortIdType;
typedef struct PduR_Core_DestInfoTypeTag
{
  PduR_Core_PortIdType destPort;
  PduIdType destPduId;
} PduR_Core_DestInfoType;
typedef P2CONST(PduR_Core_DestInfoType, TYPEDEF, PDUR_CONST) PduR_Core_DestITypePtr;
typedef enum
{
  PDUR_UNINIT = 0,
  PDUR_ONLINE = 1,
  PDUR_REDUCED = 2
} PduR_Core_StateType;
typedef P2CONST(uint8, TYPEDEF, PDUR_CONST) PduR_Uint8PbPtr;
typedef P2CONST(uint16, TYPEDEF, PDUR_CONST) PduR_Uint16PbPtr;
typedef P2FUNC(Std_ReturnType, PDUR_APPL_CODE, PduR_Core_TransmitFctPtrType) (PduIdType txPduId, P2CONST(PduInfoType, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpIfRxIndicationFctPtrType) (PduIdType UpRxPduId, PDUR_RXINDICATION_TYPE PDUR_RXINDICATION_PARA);
typedef P2FUNC(PDUR_TRIGGERTRANSMIT_RETURN, PDUR_APPL_CODE, PduR_UpIfTriggerTransmitFctPtrType) (PduIdType UpTxPduId, PDUR_TRIGGERTRANSMIT_TYPE PDUR_TRIGGERTRANSMIT_PARA);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpIfTxConfirmationFctPtrType) (PduIdType UpTxPduId);
typedef P2FUNC(BufReq_ReturnType, PDUR_APPL_CODE, PduR_UpTpProvideTxBufferFctPtrType) (PduIdType UpTxPduId, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr, uint16 Length);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpTpTxConfirmationFctPtrType) (PduIdType UpTxPduId, NotifResultType Result);
typedef P2FUNC(BufReq_ReturnType, PDUR_APPL_CODE, PduR_UpTpProvideRxBufferFctPtrType) (PduIdType UpRxPduId, PduLengthType TpSduLength, P2VAR(PduInfoTypeApplPtr, AUTOMATIC, PDUR_APPL_DATA) PduInfoPtr);
typedef P2FUNC(void, PDUR_APPL_CODE, PduR_UpTpRxIndicationFctPtrType) (PduIdType UpRxPduId, NotifResultType Result);
typedef struct PduR_PBConfigTypeTag
{
  PduIdType RxCanIf2UpCnt;
  PduR_Core_DestITypePtr RxCanIf2Up;
  PduIdType TxCanIf2UpCnt;
  PduR_Core_DestITypePtr TxCanIf2Up;
  PduIdType RxCanTp2UpCnt;
  PduR_Core_DestITypePtr RxCanTp2Up;
  PduIdType TxCanTp2UpCnt;
  PduR_Core_DestITypePtr TxCanTp2Up;
  PduIdType TxCom2LoCnt;
  PduR_Core_DestITypePtr TxCom2Lo;
  PduIdType TxDcm2LoCnt;
  PduR_Core_DestITypePtr TxDcm2Lo;
} PduR_PBConfigType;



#endif /* PDUR_TYPES_H */
