/* -----------------------------------------------------------------------------
  Filename:    Vmm_Lcfg.c
  Description: Toolversion: 11.08.02.01.30.01.24.00.00.00
               
               Serial Number: CBD1300124
               Customer Info: Nxtr Automotive Corporation
                              Package: MSR_Vector_SLP3
                              Micro: TMS570LS30376USC
                              Compiler: TexasInstruments ccs 4.9.2
               
               
               Generator Fwk   : GENy 
               Generator Module: Vmm
               
               Configuration   : C:\SynergyProjects\Haitec_LC_EPS_TMS570-nzx5jd\Haitec_LC_EPS_TMS570\Tools\AsrProject\Config\ECUC\EPS.ecuc.vdsxml
               
               ECU: 
                       TargetSystem: Hw_Tms470/570Cpu (Dcan)
                       Compiler:     TexasInstruments
                       Derivates:    TMS570LS30316U
               
               Channel "CAN00":
                       Databasefile: 
                       Bussystem:    CAN
                       Manufacturer: Vector
                       Node:         CanStateManagerConfiguration

  Generated by , 2013-08-15  12:16:19
 ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
  C O P Y R I G H T
 -------------------------------------------------------------------------------
  Copyright (c) 2001-2011 by Vctr Informatik GmbH. All rights reserved.
 
  This software is copyright protected and proprietary to Vctr Informatik 
  GmbH.
  
  Vctr Informatik GmbH grants to you only those rights as set out in the 
  license conditions.
  
  All other rights remain with Vctr Informatik GmbH.
 -------------------------------------------------------------------------------
 ----------------------------------------------------------------------------- */

/* -----------------------------------------------------------------------------
    &&&~ INCLUDES
 ----------------------------------------------------------------------------- */

#include "Vmm.h"


/* -----------------------------------------------------------------------------
    &&&~ CONST VALUES
 ----------------------------------------------------------------------------- */

#define VMM_START_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint8, VMM_VAR_NOINIT) VMM_BusSMToVmmChannel[1] = 
{
  0
};
CONST(uint8, VMM_VAR_NOINIT) VMM_ChannelCount = 1;
#define VMM_STOP_SEC_CONST_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#define VMM_START_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(Com_PduGroupIdType, VMM_VAR_NOINIT) Vmm_ComCtrlRxGroup[1] = 
{
  0xFF
};
CONST(Com_PduGroupIdType, VMM_VAR_NOINIT) Vmm_ComCtrlTxGroup[1] = 
{
  0xFF
};
CONST(Com_PduGroupIdType, VMM_VAR_NOINIT) Vmm_BusSMRxGroup[1] = 
{
  PduGrp_EPAS__CAN00_Rx
};
CONST(Com_PduGroupIdType, VMM_VAR_NOINIT) Vmm_BusSMTxGroup[1] = 
{
  PduGrp_EPAS__CAN00_Tx
};
#define VMM_STOP_SEC_CONST_UNSPECIFIED
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

#if (VMM_CRC_CHECK == STD_ON)
#define VMM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, VMM_CONST) Vmm_PrecompileCRC = (uint32) 0x240F602F;
#define VMM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"


#endif

#define VMM_START_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

CONST(uint32, VMM_VAR_NOINIT) Vmm_GeneratorVersion = 0x010701;
#define VMM_STOP_SEC_CONST_32BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



/* -----------------------------------------------------------------------------
    &&&~ RAM VALUES
 ----------------------------------------------------------------------------- */

#define VMM_START_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

VAR(boolean, VMM_VAR_NOINIT) Vmm_BusSMInitFlag[1];
VAR(boolean, VMM_VAR_NOINIT) Vmm_ComCtrlComRx[1];
VAR(boolean, VMM_VAR_NOINIT) Vmm_ComCtrlComTx[1];
VAR(boolean, VMM_VAR_NOINIT) Vmm_ComTxState[1];
VAR(boolean, VMM_VAR_NOINIT) Vmm_ComRxState[1];
VAR(boolean, VMM_VAR_NOINIT) Vmm_BusSMDMState[1];
#define VMM_STOP_SEC_VAR_NOINIT_8BIT
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"



/* -----------------------------------------------------------------------------
    &&&~ FUNCTION DEFINITION
 ----------------------------------------------------------------------------- */

#define VMM_START_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"

FUNC(void, VMM_CODE) Vmm_SwitchNm(NetworkHandleType Channel, boolean txState)
{
  switch(Channel)
  {
    case 0:
    {
      break;
    }
    default:
    {
      break;
    }
  }
}


#define VMM_STOP_SEC_CODE
/* PRQA S 5087 1 */ /* MD_MSR_19.1 */
#include "MemMap.h"




