/*******************************************************************************
* Copyright 2014 Nxtr Automotive, All Rights Reserved.
* Nxtr Confidential
*
* Module File Name  : T1_Fast.inc
* Module Description: GliwaT1 conditional include file
* Product           : Gen II Plus - EA3.0
* Author            : Owen Tosh
*******************************************************************************/
/*******************************************************************************
* Version Control:
* %version:          1 %
* %derived_by:       nzx5jd %
*******************************************************************************/
/*******************************************************************************
* Change History:
* Date      Rev      Author    Change Description
* --------  -------  --------  ------------------------------------------------
* 12/18/14   1       OT        Initial version
*******************************************************************************/

/*
*  This is the blank file that will be overlayed with a GliwaT1 integration for
*  a metrics build.  It is intentionally left blank for all other builds.
*/
